#!/usr/bin/env python3
"""
RK4 Particle Loss Diagnostic — Particle ID Tracking Version

Uses the new ParticleID + ElementID fields exported in VTU files to:
  1. Track exactly which particles are lost between consecutive RK4 export steps
  2. For each lost particle: report its last-known position, element, and region
  3. CPU 3×3×3 replay on LAST-KNOWN positions of lost particles
  4. Velocity interpolation analysis: check if barycentric interpolation produces
     artificial velocities at those positions (the suspected root cause)
  5. Report spatial distribution of losses and element-level statistics

Requires: VTU files with ParticleID and ElementID PointData arrays
          (generated by benchmark_l2_search_methods_with-export.py)
"""

import os
os.environ['XLA_PYTHON_CLIENT_PREALLOCATE'] = 'false'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
os.environ['JAX_PLATFORMS'] = 'cuda,cpu'

import numpy as np
import time
import glob
import re
from pathlib import Path
from collections import defaultdict

# ── Mesh loading (exact benchmark pattern) ───────────────────────────────────
from jaxtrace.gpu.mesh_loader_timedep import load_velocity_sequence_from_pvtu
from jaxtrace.gpu.mesh_deduplication import deduplicate_nodes

# ── Octree builder ────────────────────────────────────────────────────────────
from jaxtrace.gpu.search.mesh_aligned_octree_vertex_multi import extract_octree_cells_vertex_multi
from jaxtrace.gpu.search.mesh_aligned_octree_single_cell import (
    find_axis_aligned_edges_single,
    encode_morton_3d_single,
)

# ── VTK reader ────────────────────────────────────────────────────────────────
try:
    import vtk
    from vtk.util.numpy_support import vtk_to_numpy
    HAS_VTK = True
except ImportError:
    HAS_VTK = False

# =============================================================================
# Configuration
# =============================================================================
MESH_BASE_PATH      = Path("/home/arhashemi/Workspace/welding/Edgar/FLA/post/0eule")
MESH_FILE_PATTERN   = "featurelessAvtk_{timestep}.pvtu"
VELOCITY_TIMESTEP_RANGE = (158, 159)
VELOCITY_FIELD_NAME = 'Displacement'

# Exported VTU directory (must have ParticleID + ElementID)
EXPORT_DIR = Path(
    "output/benchmark_with_export_fixed/"
    "Mesh-Aligned_Multi-Cell_+_3×3×3_Local_(Option_A_-_Phase_2)"
)

# Analysis scope
MAX_STEPS_TO_LOAD  = 10         # Only analyse first N exported files
Z_MIN_FILTER       = -0.0035    # Only consider particles with z > this value

# CPU replay + velocity analysis budget
MAX_LOST_PARTICLES_TO_ANALYZE = 200  # Max lost particles for detailed analysis

# =============================================================================
# Helpers
# =============================================================================

def point_in_tet_numpy(pos, vertices, tol=-1e-6):
    """Double-precision CPU point-in-tet (barycentric)."""
    v0, v1, v2, v3 = vertices
    e1, e2, e3 = v1 - v0, v2 - v0, v3 - v0
    vp = pos - v0
    V0 = np.dot(e1, np.cross(e2, e3))
    if abs(V0) < 1e-30:
        return False
    l1 = np.dot(vp, np.cross(e2, e3)) / V0
    l2 = np.dot(e1, np.cross(vp, e3)) / V0
    l3 = np.dot(e1, np.cross(e2, vp)) / V0
    l0 = 1.0 - l1 - l2 - l3
    return l0 >= tol and l1 >= tol and l2 >= tol and l3 >= tol


def barycentric_coords_numpy(pos, vertices):
    """Compute barycentric coordinates (double precision). Returns (b0, b1, b2, b3)."""
    v0, v1, v2, v3 = vertices
    e1, e2, e3 = v1 - v0, v2 - v0, v3 - v0
    vp = pos - v0

    d00 = np.dot(e1, e1)
    d01 = np.dot(e1, e2)
    d02 = np.dot(e1, e3)
    d11 = np.dot(e2, e2)
    d12 = np.dot(e2, e3)
    d22 = np.dot(e3, e3)

    dp0 = np.dot(vp, e1)
    dp1 = np.dot(vp, e2)
    dp2 = np.dot(vp, e3)

    det = d00 * (d11*d22 - d12*d12) - d01 * (d01*d22 - d02*d12) + d02 * (d01*d12 - d02*d11)
    if abs(det) < 1e-30:
        return 0.25, 0.25, 0.25, 0.25  # degenerate

    b1 = (dp0 * (d11*d22 - d12*d12) - d01 * (dp1*d22 - dp2*d12) + d02 * (dp1*d12 - dp2*d11)) / det
    b2 = (d00 * (dp1*d22 - dp2*d12) - dp0 * (d01*d22 - d02*d12) + d02 * (d01*dp2 - d02*dp1)) / det
    b3 = (d00 * (d11*dp2 - d12*dp1) - d01 * (d01*dp2 - d02*dp1) + dp0 * (d01*d12 - d02*d11)) / det
    b0 = 1.0 - b1 - b2 - b3

    return b0, b1, b2, b3


def interpolate_velocity_cpu(pos, elem_id, node_positions, connectivity, velocity_field):
    """
    CPU velocity interpolation (exact match to GPU code).
    Returns: (velocity_vector, barycentric_coords, node_velocities)
    """
    nodes_idx = connectivity[elem_id]
    nodes = node_positions[nodes_idx].astype(np.float64)
    node_vels = velocity_field[nodes_idx].astype(np.float64)
    pos64 = pos.astype(np.float64)

    b0, b1, b2, b3 = barycentric_coords_numpy(pos64, nodes)
    vel = b0 * node_vels[0] + b1 * node_vels[1] + b2 * node_vels[2] + b3 * node_vels[3]

    return vel, (b0, b1, b2, b3), node_vels


def load_vtu_with_ids(vtu_path):
    """
    Load VTU file with ParticleID and ElementID arrays.
    Returns: (positions, particle_ids, element_ids) or (positions, None, None) if no IDs.
    """
    if HAS_VTK:
        reader = vtk.vtkXMLUnstructuredGridReader()
        reader.SetFileName(str(vtu_path))
        reader.Update()
        ugrid = reader.GetOutput()

        positions = vtk_to_numpy(ugrid.GetPoints().GetData()).astype(np.float32)

        # Try to read ParticleID
        pid_arr = ugrid.GetPointData().GetArray("ParticleID")
        particle_ids = vtk_to_numpy(pid_arr).astype(np.int32) if pid_arr is not None else None

        # Try to read ElementID
        eid_arr = ugrid.GetPointData().GetArray("ElementID")
        element_ids = vtk_to_numpy(eid_arr).astype(np.int32) if eid_arr is not None else None

        return positions, particle_ids, element_ids
    else:
        import meshio
        m = meshio.read(str(vtu_path))
        positions = m.points.astype(np.float32)
        particle_ids = m.point_data.get("ParticleID", None)
        element_ids = m.point_data.get("ElementID", None)
        if particle_ids is not None:
            particle_ids = particle_ids.astype(np.int32)
        if element_ids is not None:
            element_ids = element_ids.astype(np.int32)
        return positions, particle_ids, element_ids


def discover_vtu_files(export_dir):
    """Return sorted list of (step_int, Path) tuples."""
    pattern = str(export_dir / "particles_step_*.vtu")
    files = sorted(glob.glob(pattern))
    result = []
    for f in files:
        m = re.search(r'particles_step_(\d+)\.vtu$', f)
        if m:
            result.append((int(m.group(1)), Path(f)))
    return result


def cpu_replay_single(pos, cell_lookup, level_cell_sizes, octree_multi,
                      node_positions, connectivity):
    """
    CPU 3×3×3 replay for one position (double precision).
    Returns: (found_elem_id, n_cells_searched, n_elems_tested, per_level_info)
    """
    morton_offset = 1 << 19
    max_coord     = 1 << 20
    total_cells = total_elems = 0
    cpu_found = -1
    per_level = []

    for level_idx in range(8):
        level = 14 - level_idx
        if level not in level_cell_sizes:
            continue
        cs = level_cell_sizes[level]
        if np.any(cs < 1e-15):
            continue

        i_b = int(np.floor(pos[0] / cs[0]))
        j_b = int(np.floor(pos[1] / cs[1]))
        k_b = int(np.floor(pos[2] / cs[2]))

        lc = le = 0
        found = False

        for di in [-1, 0, 1]:
            for dj in [-1, 0, 1]:
                for dk in [-1, 0, 1]:
                    ii = max(0, min(i_b + di + morton_offset, max_coord - 1))
                    jj = max(0, min(j_b + dj + morton_offset, max_coord - 1))
                    kk = max(0, min(k_b + dk + morton_offset, max_coord - 1))
                    mort = encode_morton_3d_single(ii, jj, kk, max_depth=21)
                    key = (mort, level)
                    if key not in cell_lookup:
                        continue
                    ci = cell_lookup[key]
                    s = octree_multi.cell_to_elements_offsets[ci]
                    e = octree_multi.cell_to_elements_offsets[ci + 1]
                    ne = e - s
                    lc += 1; le += ne
                    total_cells += 1; total_elems += ne
                    for ei in range(ne):
                        eid = int(octree_multi.cell_to_elements_data[s + ei])
                        v = node_positions[connectivity[eid]].astype(np.float64)
                        if point_in_tet_numpy(pos, v):
                            cpu_found = eid
                            found = True
                            break
                    if found:
                        break
                if found:
                    break
            if found:
                break

        per_level.append((level, lc, le))
        if found:
            break

    return cpu_found, total_cells, total_elems, per_level


# =============================================================================
# Main
# =============================================================================

def main():
    print("=" * 80)
    print("RK4 Particle Loss Diagnostic — Particle ID Tracking")
    print(f"  Export dir:     {EXPORT_DIR}")
    print(f"  Max steps:      {MAX_STEPS_TO_LOAD}")
    print(f"  Z filter:       z > {Z_MIN_FILTER}")
    print("=" * 80)

    # ══════════════════════════════════════════════════════════════════════════
    # [1] Load mesh
    # ══════════════════════════════════════════════════════════════════════════
    print("\n[1/6] Loading mesh...")
    t0 = time.time()
    node_positions, connectivity, velocity_sequence = load_velocity_sequence_from_pvtu(
        base_path=MESH_BASE_PATH, file_pattern=MESH_FILE_PATTERN,
        timestep_range=VELOCITY_TIMESTEP_RANGE, field_name=VELOCITY_FIELD_NAME,
        verbose=False,
    )
    n_elements = connectivity.shape[0]
    print(f"  Loaded in {time.time()-t0:.1f}s "
          f"({n_elements:,} elements, {node_positions.shape[0]:,} nodes)")

    print("  Deduplicating...")
    node_positions, connectivity, n_dup, velocity_sequence = deduplicate_nodes(
        node_positions, connectivity, velocity_sequence=velocity_sequence, verbose=False
    )
    print(f"  Removed {n_dup:,} duplicates → {node_positions.shape[0]:,} nodes")

    mesh_min = node_positions.min(axis=0).astype(np.float64)
    mesh_max = node_positions.max(axis=0).astype(np.float64)
    print(f"  Mesh bbox: ({mesh_min[0]:.6f},{mesh_min[1]:.6f},{mesh_min[2]:.6f})"
          f" → ({mesh_max[0]:.6f},{mesh_max[1]:.6f},{mesh_max[2]:.6f})")

    # Use first velocity timestep for interpolation analysis
    vel_field_0 = velocity_sequence[0]  # (n_nodes, 3)
    print(f"  Velocity field shape: {vel_field_0.shape}")
    print(f"  Velocity magnitude range: [{np.linalg.norm(vel_field_0, axis=1).min():.6e}, "
          f"{np.linalg.norm(vel_field_0, axis=1).max():.6e}]")

    # ══════════════════════════════════════════════════════════════════════════
    # [2] Build octree + CPU lookup
    # ══════════════════════════════════════════════════════════════════════════
    print("\n[2/6] Building multi-cell octree...")
    t0 = time.time()
    octree_multi = extract_octree_cells_vertex_multi(
        node_positions, connectivity, tolerance=1e-6, verbose=False
    )
    print(f"  {octree_multi.n_cells:,} cells, "
          f"{octree_multi.elements_per_cell_mean:.1f} elem/cell  "
          f"({time.time()-t0:.1f}s)")

    # CPU lookup tables
    cell_levels_cpu = octree_multi.cell_levels
    cell_sizes_cpu  = octree_multi.cell_sizes
    cell_morton_cpu = octree_multi.cell_morton_codes

    level_cell_sizes = {}
    for lvl in range(21):
        mask = cell_levels_cpu == lvl
        if mask.any():
            level_cell_sizes[lvl] = cell_sizes_cpu[mask][0].astype(np.float64)
    print(f"  Active levels: {sorted(level_cell_sizes.keys())}")

    cell_lookup = {}
    for ci in range(octree_multi.n_cells):
        key = (int(cell_morton_cpu[ci]), int(cell_levels_cpu[ci]))
        cell_lookup[key] = ci
    print(f"  Lookup: {len(cell_lookup):,} cells")

    # ══════════════════════════════════════════════════════════════════════════
    # [3] Load VTU files with particle IDs
    # ══════════════════════════════════════════════════════════════════════════
    print("\n[3/6] Loading exported VTU files with particle IDs...")
    vtu_files = discover_vtu_files(EXPORT_DIR)
    if not vtu_files:
        print(f"  ERROR: No VTU files in {EXPORT_DIR}")
        return
    vtu_files = vtu_files[:MAX_STEPS_TO_LOAD]
    print(f"  Loading {len(vtu_files)} files: steps "
          f"{vtu_files[0][0]}..{vtu_files[-1][0]}")

    # Load all steps: dict of {particle_id: (position, element_id)}
    step_data = []  # list of (step, {pid: (pos, eid)})

    for step, path in vtu_files:
        positions, particle_ids, element_ids = load_vtu_with_ids(path)

        if particle_ids is None:
            print(f"  ERROR: Step {step} has no ParticleID field!")
            print(f"  Re-run benchmark_l2_search_methods_with-export.py to generate VTUs with IDs.")
            return

        # Apply z-filter
        z_mask = positions[:, 2] > Z_MIN_FILTER
        pos_f = positions[z_mask]
        pid_f = particle_ids[z_mask]
        eid_f = element_ids[z_mask] if element_ids is not None else None

        # Build pid→(pos, eid) dict
        pid_dict = {}
        for i in range(len(pid_f)):
            eid = int(eid_f[i]) if eid_f is not None else -1
            pid_dict[int(pid_f[i])] = (pos_f[i].copy(), eid)

        step_data.append((step, pid_dict))
        n_active = sum(1 for v in pid_dict.values() if v[1] >= 0)
        print(f"  Step {step:6d}: {len(positions):,} raw → {len(pid_dict):,} after z>{Z_MIN_FILTER}"
              f"  (active={n_active:,}, lost_elem={len(pid_dict)-n_active:,})")

    # ══════════════════════════════════════════════════════════════════════════
    # [4] Find lost particles between consecutive steps
    # ══════════════════════════════════════════════════════════════════════════
    print("\n[4/6] Identifying lost particles between consecutive steps...")
    print("=" * 80)

    all_lost_particles = []  # (lost_step, pid, last_pos, last_eid)

    for idx in range(1, len(step_data)):
        step_prev, dict_prev = step_data[idx - 1]
        step_curr, dict_curr = step_data[idx]

        pids_prev = set(dict_prev.keys())
        pids_curr = set(dict_curr.keys())

        # Particles present in prev but missing in curr
        lost_pids = pids_prev - pids_curr

        # Particles that became inactive (eid = -1) in curr
        newly_inactive = set()
        for pid in pids_curr:
            if pid in pids_prev:
                _, eid_prev = dict_prev[pid]
                _, eid_curr = dict_curr[pid]
                if eid_prev >= 0 and eid_curr < 0:
                    newly_inactive.add(pid)

        print(f"\n  Step {step_prev} → {step_curr}:")
        print(f"    Previous: {len(pids_prev):,} particles")
        print(f"    Current:  {len(pids_curr):,} particles")
        print(f"    Disappeared (not in export): {len(lost_pids):,}")
        print(f"    Newly inactive (eid→-1):     {len(newly_inactive):,}")

        # Record lost particles with their LAST KNOWN position/element
        for pid in lost_pids:
            pos, eid = dict_prev[pid]
            all_lost_particles.append((step_curr, pid, pos, eid))

        for pid in newly_inactive:
            pos_prev, eid_prev = dict_prev[pid]
            pos_curr, eid_curr = dict_curr[pid]
            all_lost_particles.append((step_curr, pid, pos_prev, eid_prev))

    print(f"\n  Total lost/inactivated particles: {len(all_lost_particles):,}")

    if len(all_lost_particles) == 0:
        print("  No particle loss detected. Done.")
        return

    # ══════════════════════════════════════════════════════════════════════════
    # [5] Analyze lost particles: spatial distribution, element info, CPU replay
    # ══════════════════════════════════════════════════════════════════════════
    print(f"\n[5/6] Analyzing lost particles (up to {MAX_LOST_PARTICLES_TO_ANALYZE})...")
    print("=" * 80)

    # Select particles for detailed analysis
    analysis_set = all_lost_particles[:MAX_LOST_PARTICLES_TO_ANALYZE]

    # Spatial distribution of all lost particles
    lost_positions = np.array([p[2] for p in all_lost_particles], dtype=np.float64)
    lost_eids = np.array([p[3] for p in all_lost_particles], dtype=np.int32)

    print(f"\n  Spatial distribution of ALL {len(all_lost_particles)} lost particles:")
    print(f"    X: [{lost_positions[:,0].min():.6f}, {lost_positions[:,0].max():.6f}]")
    print(f"    Y: [{lost_positions[:,1].min():.6f}, {lost_positions[:,1].max():.6f}]")
    print(f"    Z: [{lost_positions[:,2].min():.6f}, {lost_positions[:,2].max():.6f}]")

    # Element stats
    valid_eids = lost_eids[lost_eids >= 0]
    print(f"\n  Last-known element stats:")
    print(f"    With valid element:   {len(valid_eids):,}")
    print(f"    Already lost (eid=-1): {(lost_eids < 0).sum():,}")

    if len(valid_eids) > 0:
        unique_elems = np.unique(valid_eids)
        print(f"    Unique elements involved: {len(unique_elems):,}")

        # Element frequency (which elements lose the most particles?)
        elem_counts = defaultdict(int)
        for eid in valid_eids:
            elem_counts[int(eid)] += 1
        top_elems = sorted(elem_counts.items(), key=lambda x: -x[1])[:20]
        print(f"\n    Top elements by loss count:")
        print(f"    {'ElemID':>10s}  {'Losses':>8s}  {'Centroid_X':>11s}  {'Centroid_Y':>11s}  {'Centroid_Z':>11s}")
        for eid, cnt in top_elems:
            centroid = node_positions[connectivity[eid]].mean(axis=0)
            print(f"    {eid:>10d}  {cnt:>8d}  {centroid[0]:>11.6f}  {centroid[1]:>11.6f}  {centroid[2]:>11.6f}")

    # ── CPU replay + velocity analysis on lost particles ─────────────────────
    print(f"\n{'='*80}")
    print(f"CPU 3×3×3 REPLAY + VELOCITY ANALYSIS on {len(analysis_set)} lost particles")
    print(f"{'='*80}")

    n_found = 0
    n_not_found = 0
    n_outside_bbox = 0
    causes = defaultdict(int)

    # Velocity interpolation anomaly tracking
    vel_anomalies = []  # (pid, pos, eid, vel, bary_coords, issue)

    for pi, (lost_step, pid, pos, last_eid) in enumerate(analysis_set):
        pos64 = pos.astype(np.float64)
        in_bbox = bool(np.all(pos64 >= mesh_min) and np.all(pos64 <= mesh_max))

        # CPU 3×3×3 replay at last-known position
        cpu_eid, nc, ne, per_level = cpu_replay_single(
            pos64, cell_lookup, level_cell_sizes,
            octree_multi, node_positions, connectivity
        )

        if cpu_eid >= 0:
            n_found += 1
            cause = "FOUND"
        elif not in_bbox:
            n_outside_bbox += 1
            cause = "OUTSIDE_BBOX"
        else:
            n_not_found += 1
            if nc == 0:
                cause = "NO_CELLS_AT_ANY_LEVEL"
            elif ne == 0:
                cause = "CELLS_EXIST_BUT_EMPTY"
            else:
                cause = "CELLS_EXIST_PIT_FAILS"
        causes[cause] += 1

        # Velocity interpolation analysis at last-known position
        vel_info = ""
        if last_eid >= 0:
            vel, bary, node_vels = interpolate_velocity_cpu(
                pos64, last_eid, node_positions, connectivity, vel_field_0
            )
            vel_mag = np.linalg.norm(vel)
            b0, b1, b2, b3 = bary
            bary_min = min(b0, b1, b2, b3)
            bary_max = max(b0, b1, b2, b3)

            # Check for anomalies
            anomaly = None
            if bary_min < -0.1:
                anomaly = f"LARGE_NEG_BARY(min={bary_min:.4f})"
            elif bary_max > 1.5:
                anomaly = f"LARGE_POS_BARY(max={bary_max:.4f})"
            elif vel_mag > 1.0:
                anomaly = f"HIGH_VEL(|v|={vel_mag:.4e})"

            # Check node velocity magnitudes
            node_vel_mags = np.linalg.norm(node_vels, axis=1)
            max_node_vel = node_vel_mags.max()
            if vel_mag > 2 * max_node_vel and vel_mag > 1e-6:
                anomaly = (anomaly or "") + f" VEL_AMPLIFIED({vel_mag:.4e}>{max_node_vel:.4e})"

            vel_info = (f"  vel=({vel[0]:+.4e},{vel[1]:+.4e},{vel[2]:+.4e}) |v|={vel_mag:.4e}"
                        f"  bary=({b0:.4f},{b1:.4f},{b2:.4f},{b3:.4f})"
                        f"  max_node_vel={max_node_vel:.4e}")

            if anomaly:
                vel_anomalies.append((pid, pos64, last_eid, vel, bary, anomaly))
                vel_info += f"  ⚠ {anomaly}"

        # Print detail for first 50 and all anomalies
        if pi < 50 or cpu_eid < 0 or anomaly:
            status = f"cpu_elem={cpu_eid}" if cpu_eid >= 0 else cause
            print(f"\n  [{pi+1:3d}] PID={pid:>6d}  lost@step={lost_step}  last_eid={last_eid}")
            print(f"        pos=({pos64[0]:+.8f},{pos64[1]:+.8f},{pos64[2]:+.8f})"
                  f"  in_bbox={'Y' if in_bbox else 'N'}  → {status}")
            if vel_info:
                print(f"       {vel_info}")

            if cpu_eid < 0 and in_bbox:
                for lvl, lc, le in per_level:
                    if lc > 0:
                        print(f"        Level {lvl}: {lc} cells, {le} elems tested")

            if cpu_eid < 0 and not in_bbox:
                under = np.maximum(mesh_min - pos64, 0)
                over  = np.maximum(pos64 - mesh_max, 0)
                for ax_i, ax_n in enumerate(['X','Y','Z']):
                    if under[ax_i] > 0:
                        print(f"        {ax_n} < mesh_min by {under[ax_i]:.6e}")
                    if over[ax_i] > 0:
                        print(f"        {ax_n} > mesh_max by {over[ax_i]:.6e}")

    # ══════════════════════════════════════════════════════════════════════════
    # [6] Velocity interpolation summary
    # ══════════════════════════════════════════════════════════════════════════
    print(f"\n{'='*80}")
    print("VELOCITY INTERPOLATION ANALYSIS")
    print(f"{'='*80}")

    if vel_anomalies:
        print(f"\n  ⚠ Found {len(vel_anomalies)} velocity anomalies:")
        for pid, pos, eid, vel, bary, issue in vel_anomalies[:30]:
            b0, b1, b2, b3 = bary
            print(f"    PID={pid:>6d}  eid={eid:>8d}  |v|={np.linalg.norm(vel):.4e}"
                  f"  bary=({b0:.4f},{b1:.4f},{b2:.4f},{b3:.4f})  {issue}")
    else:
        print("  No velocity interpolation anomalies detected at last-known positions.")

    # Global velocity statistics at lost-particle elements
    print(f"\n  Velocity statistics at last-known elements of lost particles:")
    vel_mags = []
    bary_mins = []
    bary_maxs = []
    z_vels = []

    for _, _, pos, last_eid in analysis_set:
        if last_eid < 0:
            continue
        pos64 = pos.astype(np.float64)
        vel, bary, node_vels = interpolate_velocity_cpu(
            pos64, last_eid, node_positions, connectivity, vel_field_0
        )
        vel_mags.append(np.linalg.norm(vel))
        bary_mins.append(min(bary))
        bary_maxs.append(max(bary))
        z_vels.append(vel[2])

    if vel_mags:
        vel_mags = np.array(vel_mags)
        bary_mins = np.array(bary_mins)
        bary_maxs = np.array(bary_maxs)
        z_vels = np.array(z_vels)

        print(f"    |v| range:     [{vel_mags.min():.6e}, {vel_mags.max():.6e}]")
        print(f"    |v| mean:      {vel_mags.mean():.6e}")
        print(f"    v_z range:     [{z_vels.min():.6e}, {z_vels.max():.6e}]")
        print(f"    v_z mean:      {z_vels.mean():.6e}")
        print(f"    v_z > 0 (upward): {(z_vels > 0).sum()}/{len(z_vels)}")
        print(f"    bary_min range: [{bary_mins.min():.6f}, {bary_mins.max():.6f}]")
        print(f"    bary_max range: [{bary_maxs.min():.6f}, {bary_maxs.max():.6f}]")
        print(f"    bary_min < 0:   {(bary_mins < 0).sum()}/{len(bary_mins)} "
              f"(particle outside its last-known element)")
        print(f"    bary_min < -0.1: {(bary_mins < -0.1).sum()}/{len(bary_mins)} "
              f"(significantly outside)")

    # ── CPU replay summary ───────────────────────────────────────────────────
    print(f"\n{'='*80}")
    print("CPU REPLAY SUMMARY (last-known positions of lost particles)")
    print(f"{'='*80}")
    print(f"  Total analyzed:        {len(analysis_set)}")
    print(f"  FOUND (CPU replay):    {n_found}")
    print(f"  OUTSIDE BBOX:          {n_outside_bbox}")
    print(f"  NOT FOUND (in bbox):   {n_not_found}")
    print()
    print(f"  Cause breakdown:")
    for cause, count in sorted(causes.items(), key=lambda x: -x[1]):
        pct = 100.0 * count / len(analysis_set) if analysis_set else 0
        print(f"    {cause:<30s}: {count:>5d} ({pct:>5.1f}%)")

    # ── RK4 Velocity Interpolation Code Analysis ─────────────────────────────
    print(f"\n{'='*80}")
    print("RK4 INTERPOLATION CODE ANALYSIS")
    print(f"{'='*80}")
    print("""
  The GPU RK4 code (rk4_fully_fused_timedep.py) has these potential issues:

  1. NEGATIVE INDEX ACCESS (connectivity[-1]):
     When elem_id = -1 (search failed), the interpolation function reads
     connectivity[-1] (Python wraps to LAST element). JAX jnp.where masks the
     output to zero, but the computation itself runs on wrong data.
     → This is safe for VELOCITY (masked to zero), but could cause issues in
       the SEARCH (L0 check of connectivity[-1] element).

  2. RK4 SUB-STEP SEARCH CHAIN:
     If stage k1 search fails (elem_k1 = -1), vel_k1 = zero, pos_k1 = pos.
     Stage k2 then searches from elem_k1 = -1 as cached element.
     L0 check: connectivity[-1] → last element → likely NOT containing pos.
     L1 search: start from -1 → masked out (should_search = False) → returns -1.
     L2 search: full octree search → should find the correct element.
     → If L2 search ALSO fails: ALL subsequent stages get zero velocity,
       and pos_final = pos (no movement). elem_final search may then also fail
       → particle permanently lost with elem_id = -1.

  3. BARYCENTRIC COORD ACCUMULATION:
     If particle is at edge/vertex of element, barycentric coords can have
     slight numerical errors. Velocity is computed correctly, but the position
     update pos_k1 = pos + 0.5*dt*vel_k1 may push the particle slightly
     outside the element. If the new position is in a registration gap
     (not covered by 3×3×3 neighborhood), the search fails.
     → This is the most likely cause of tetrahedral-shaped voids.

  4. SINGLE VELOCITY FIELD PER RK4 STEP:
     All 4 stages (k1..k4) use the SAME velocity_field[vel_idx], even though
     stages k2/k3 evaluate at t+dt/2 and k4 at t+dt. For time-dependent flows,
     this means the time interpolation is missing. If the real code uses
     different timesteps for different stages, this could cause different
     trajectories than FEMUSS.
""")

    # ── Loss rate evolution ──────────────────────────────────────────────────
    print(f"\n{'='*80}")
    print(f"PARTICLE COUNT EVOLUTION (z > {Z_MIN_FILTER})")
    print(f"{'='*80}")
    print(f"  {'Step':>6s}  {'N_total':>10s}  {'N_active':>10s}  {'Δ_total':>8s}  {'Loss%_cum':>10s}")
    print("  " + "-" * 50)
    n_first = len(step_data[0][1])
    prev = n_first
    for step, pid_dict in step_data:
        n = len(pid_dict)
        n_active = sum(1 for v in pid_dict.values() if v[1] >= 0)
        delta = n - prev
        cum_loss = 100.0 * (n_first - n) / n_first if n_first > 0 else 0
        print(f"  {step:>6d}  {n:>10,}  {n_active:>10,}  {delta:>+8,}  {cum_loss:>9.3f}%")
        prev = n

    print(f"\n{'='*80}")
    print("DONE")
    print(f"{'='*80}")


if __name__ == "__main__":
    main()
