#!/usr/bin/env python3
"""Survey FSW case folders and report what is available.

READ-ONLY.  Opens nothing for writing under the surveyed root and creates no
files there; all output goes to --out (default: the current directory).

Written for LUMI, where the cases live in a colleague's folder:

    python3 survey_lumi_cases.py \
        --root /scratch/project_465002752/lorenzgl/Cases/PinShapes \
        --out  /scratch/project_465002752/hashemia/case_survey

Over a slow filesystem the full scan can take a while, so:
  * metadata (.info/.mat) is parsed by reading a few KB, not the whole file
  * PVTU field discovery reads ONLY the header of the last timestep by default
  * --quick skips PVTU inspection entirely (structure + parameters only)
  * --deep also opens the last PVTU with VTK for mesh size and value ranges
    (needs vtk; without it the script still works, just with less detail)

Outputs ``case_survey.csv`` and ``case_survey.md``.
"""

from __future__ import annotations

import argparse
import csv
import os
import re
import sys
import time
from pathlib import Path

# Fields the damage pipeline needs; reported per case so unusable cases are
# obvious before anyone spends GPU time on them.
REQUIRED_FIELDS = ("Displacement", "Pressure", "Temperature", "LEVEL")

# .info keys worth extracting. Key -> (regex, cast)
INFO_KEYS = {
    "pin_geometry":     r"Pin geometry:\s*(.+?)\s*$",
    "shoulder":         r"Shoulder geometry:\s*(.+?)\s*$",
    "stl":              r"STL name:\s*(.+?)\s*$",
    "rotation_signed":  r"Signed Rotational speed:\s*([-\d.]+)",
    "rotation_text":    r"Rotation Orientation:\s*(.+?)\s*$",
    "advancing_mm_min": r"Advancing speed:\s*([\d.]+)\s*mm/min",
    "tilt_deg":         r"Tilt angle:\s*([-\d.]+)",
    "plunge":           r"Plunge depth:\s*([-\d.]+)",
    "plate_height":     r"Height:\s*([\d.]+)",
    "plate_width":      r"Width:\s*([\d.]+)",
    "revolutions":      r"Revolutions:\s*([\d.]+)",
    "steps_per_rev":    r"Steps per revolution:\s*([\d.]+)",
    "n_steps":          r"Total number of time steps:\s*([\d.]+)",
    "dt":               r"Time step size\s*([\d.eE+-]+)",
    "friction_model":   r"Friction model:\s*(.+?)\s*$",
}


def parse_info(path: Path) -> dict:
    """Pull process parameters out of a GiD .info file."""
    out = {}
    try:
        text = path.read_text(errors="ignore")
    except OSError as exc:
        return {"info_error": str(exc)}
    for key, pattern in INFO_KEYS.items():
        m = re.search(pattern, text, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip()
    return out


# Keys inside the FSW_ANALISIS / PROCESS_PARAMETERS block of <case>.som.dat.
# These are the values the SOLVER actually used, and they override the .info
# file, which is generated by the GUI and is not always kept in sync.
SOM_KEYS = {
    "som_rpm":          r"RPM:\s*([-\d.eE+]+)",
    "som_tilt_deg":     r"TILT_ANGLE:\s*([-\d.eE+]+)",
    "som_plunge":       r"PLUNGING_DEPTH:\s*([-\d.eE+]+)",
    "som_vert_load":    r"VERTICAL_LOADING:\s*([-\d.eE+]+)",
    "som_tool_angle0":  r"INITIAL_TOOL_ANGLE:\s*([-\d.eE+]+)",
    "som_tool":         r"TOOL:\s*(.+?)\s*$",
    "som_time_step":    r"TIME_STEP:\s*([\d.eE+-]+)",
    "som_time_interval": r"TIME_INTERVAL:\s*([\d.eE+-]+)",
    "som_friction":     r"MODEL:\s*(.+?)\s*$",
    "som_travelling_bc": r"TRAVELLING BOCONDITION:\s*(\S+)",
    "som_frame_ref":    r"FRAME_OF_REFERENCE:\s*(\S+)",
}


def parse_som_dat(path: Path) -> dict:
    """Authoritative process parameters from <case>.som.dat.

    The .info file is GUI-generated and can disagree with what was actually
    solved (cylA.info says "counterclockwise" while its signed RPM is -600,
    and the velocity field confirms CW).  This block is the ground truth.
    """
    out = {}
    try:
        text = path.read_text(errors="ignore")
    except OSError as exc:
        return {"som_error": str(exc)}
    for key, pattern in SOM_KEYS.items():
        m = re.search(pattern, text, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip()
    return out


def parse_fix(path: Path) -> dict:
    """Prescribed nodal boundary values from a .fix file.

    Layout is ``<node> <code> <vx> <vy> <vz> ...``.  Most nodes are fully
    constrained to zero; any NON-ZERO prescribed value is an applied velocity
    and is what actually drives the flow, so it is reported explicitly.
    """
    out = {}
    try:
        vals = []
        n_rows = 0
        with open(path, "r", errors="ignore") as fh:
            for line in fh:
                parts = line.split()
                if len(parts) < 5 or not parts[0].isdigit():
                    continue
                n_rows += 1
                try:
                    v = [float(parts[2]), float(parts[3]), float(parts[4])]
                except ValueError:
                    continue
                if any(abs(c) > 1e-12 for c in v):
                    vals.append(v)
        out["fix_n_rows"] = n_rows
        out["fix_n_nonzero"] = len(vals)
        if vals:
            import statistics as st
            for i, ax in enumerate("xyz"):
                col = [v[i] for v in vals]
                nz = [c for c in col if abs(c) > 1e-12]
                if nz:
                    out[f"fix_v{ax}_max"] = f"{max(nz, key=abs):.6g}"
                    out[f"fix_v{ax}_median"] = f"{st.median(nz):.6g}"
    except OSError as exc:
        out["fix_error"] = str(exc)
    return out


def parse_run_jaxtrace(case_dir: Path) -> dict:
    """Read the per-case run_jaxtrace.sh for the cyclic velocity window.

    VEL_START/VEL_END define ONE FULL REVOLUTION of the tool in timestep
    indices, already worked out per case.  This is the authoritative window
    for any phase-resolved analysis: threaded, fluted, flats and tilted tools
    are periodic at omega, so a single snapshot is one arbitrary phase.
    """
    out = {}
    f = case_dir / "run_jaxtrace.sh"
    if not f.is_file():
        return out
    try:
        text = f.read_text(errors="ignore")
    except OSError as exc:
        return {"runjax_error": str(exc)}

    for key, pat in (("vel_start", r"^VEL_START=\s*(\d+)"),
                     ("vel_end",   r"^VEL_END=\s*(\d+)"),
                     ("rk4_n_steps", r"^N_STEPS=\s*(\d+)"),
                     ("mesh_pattern", r'^MESH_PATTERN="([^"]*)"'),
                     ("mesh_subdir",  r'^MESH_SUBDIR="([^"]*)"')):
        m = re.search(pat, text, re.MULTILINE)
        if m:
            out[key] = m.group(1).strip()

    vs, ve = _f(out.get("vel_start")), _f(out.get("vel_end"))
    if vs is not None and ve is not None:
        out["vel_n_steps"] = int(ve - vs + 1)
    out["has_run_jaxtrace"] = 1
    return out


def scan_data_folder(case_dir: Path) -> dict:
    """Read the solver input files under <case>.gid/data/.

    Layout: data/<stage>/<prefix>.som.dat, .som.fix, .dom.*, .lev.*, .tem.*
    Stages are e.g. 0eule, 1eule.  The LAST stage is the one that produced
    the final result, so it is preferred; the count is reported so a case
    with multiple stages is visible.
    """
    out = {}
    data = case_dir / "data"
    if not data.is_dir():
        out["data_dir"] = ""
        return out
    try:
        stages = sorted(d for d in data.iterdir() if d.is_dir())
    except OSError as exc:
        return {"data_error": str(exc)}

    out["n_stages"] = len(stages)
    out["stages"] = "|".join(d.name for d in stages)

    # TWO LAYOUTS EXIST:
    #   (a) staged   data/<stage>/<prefix>.som.dat   e.g. cylA: 0eule/1eule/...
    #   (b) flat     data/<prefix>.som.dat           e.g. the LUMI PinShapes set
    # Handle both: prefer the last stage that holds a .som.dat, else fall back
    # to data/ itself.
    with_som = [d for d in stages if any(d.glob("*.som.dat"))]
    if with_som:
        # Cases interleave Eulerian and particle stages (0eule, 0part, ...);
        # only the *eule ones carry solver input, so the last stage overall is
        # often a particle stage with nothing in it.
        stage = with_som[-1]
        out["stage_used"] = stage.name
        out["n_stages_with_som"] = len(with_som)
        out["data_layout"] = "staged"
    elif any(data.glob("*.som.dat")):
        stage = data
        out["stage_used"] = "(flat)"
        out["n_stages_with_som"] = 0
        out["data_layout"] = "flat"
    else:
        out["stage_used"] = ""
        out["data_layout"] = "unknown"
        out["data_note"] = "no .som.dat under data/ or its subfolders"
        return out

    try:
        som_dats = sorted(stage.glob("*.som.dat"))
        if som_dats:
            out["som_file"] = str(som_dats[0].relative_to(case_dir))
            out.update(parse_som_dat(som_dats[0]))
        som_fix = sorted(stage.glob("*.som.fix"))
        if som_fix:
            out.update(parse_fix(som_fix[0]))
        # Any other per-stage inputs, listed so nothing is silently ignored.
        out["stage_files"] = "|".join(sorted(f.name for f in stage.glob("*")))[:400]
    except OSError as exc:
        out["data_error"] = str(exc)
    return out


def parse_material(path: Path) -> dict:
    """Material name, and whether the Norton viscosity tables are present."""
    out = {}
    try:
        text = path.read_text(errors="ignore")
    except OSError:
        return out
    m = re.search(r"MATERIAL:\s*(\S+)", text)
    if m:
        out["material"] = m.group(1)
    out["has_norton"] = int(
        "Plastic_viscosity" in text and "Exponent_viscosity" in text
    )
    return out


def pvtu_fields(path: Path) -> list:
    """Field names from a PVTU header, without parsing the whole file.

    The <PPointData> block sits near the top, so a bounded read is enough and
    avoids pulling megabytes over a slow mount.
    """
    try:
        with open(path, "r", errors="ignore") as fh:
            head = fh.read(8192)
    except OSError:
        return []
    block = re.search(r"<PPointData.*?</PPointData>", head, re.S)
    if not block:
        # Some writers put it lower; try a larger but still bounded read.
        try:
            with open(path, "r", errors="ignore") as fh:
                head = fh.read(262144)
        except OSError:
            return []
        block = re.search(r"<PPointData.*?</PPointData>", head, re.S)
        if not block:
            return []
    return re.findall(r'Name="([^"]+)"', block.group(0))


# ⚠️ The file prefix inside a case folder need not match the folder name.
# These cases were produced by copying a reference case, renaming the folder,
# changing the parameters and re-running.  So D4.gid can legitimately contain
# C2_*.pvtu and A1.info: those files ARE that case's own inputs and output,
# carrying its parameters.  The stale prefix is a naming artefact only, and is
# reported (copied_from) rather than treated as an error.


def find_post_dir(case_dir: Path):
    """Locate the directory holding the PVTUs.

    Layouts seen so far:
        <case>.gid/post/*.pvtu            (A2, PinShapes)
        <case>.gid/post/0eule/*.pvtu      (cylA)
    """
    post = case_dir / "post"
    if not post.is_dir():
        return None
    try:
        if any(post.glob("*.pvtu")):
            return post
        for sub in sorted(post.iterdir()):
            if sub.is_dir() and any(sub.glob("*.pvtu")):
                return sub
    except OSError:
        return None
    return None


def timestep_index(name: str):
    """Trailing integer in a PVTU stem, e.g. 'A1_151' -> 151."""
    m = re.search(r"_(\d+)$", Path(name).stem)
    return int(m.group(1)) if m else None


def survey_case(case_dir: Path, quick: bool, deep: bool) -> dict:
    """Inspect one <name>.gid folder. Never writes."""
    rec = {
        "case": case_dir.name.replace(".gid", ""),
        "family": case_dir.parent.name,
        "path": str(case_dir),
    }

    # The file prefix need not match the folder: D1.gid contains A1.info.
    prefix = None
    try:
        infos = sorted(case_dir.glob("*.info"))
        if infos:
            prefix = infos[0].stem
            rec.update(parse_info(infos[0]))
        mats = sorted(case_dir.glob("*.mat"))
        if mats:
            rec.update(parse_material(mats[0]))
    except OSError as exc:
        rec["scan_error"] = str(exc)
    rec["file_prefix"] = prefix or ""
    rec["prefix_matches_folder"] = int(
        bool(prefix) and prefix == rec["case"]
    )

    # Solver inputs under data/ — authoritative, unlike the GUI .info file.
    rec.update(scan_data_folder(case_dir))

    # Per-case cyclic velocity window (one full tool revolution).
    rec.update(parse_run_jaxtrace(case_dir))

    # Flag disagreements between the GUI file and what was actually solved.
    disagree = []
    inf_rpm, som_rpm = _f(rec.get("rotation_signed")), _f(rec.get("som_rpm"))
    if inf_rpm is not None and som_rpm is not None and abs(inf_rpm - som_rpm) > 1e-6:
        disagree.append(f"rpm info={inf_rpm} som={som_rpm}")
    inf_tilt, som_tilt = _f(rec.get("tilt_deg")), _f(rec.get("som_tilt_deg"))
    if inf_tilt is not None and som_tilt is not None and abs(inf_tilt - som_tilt) > 1e-6:
        disagree.append(f"tilt info={inf_tilt} som={som_tilt}")
    rec["info_som_disagree"] = "; ".join(disagree)

    post = find_post_dir(case_dir)
    if post is None:
        rec["status"] = "no-post"
        rec["n_pvtu"] = 0
        return rec
    rec["post_dir"] = str(post.relative_to(case_dir))

    try:
        pvtus = sorted(post.glob("*.pvtu"))
    except OSError as exc:
        rec["status"] = "post-unreadable"
        rec["scan_error"] = str(exc)
        return rec

    rec["n_pvtu"] = len(pvtus)
    if not pvtus:
        rec["status"] = "no-pvtu"
        return rec

    # Take the highest-numbered PVTU whatever its prefix: a copied case keeps
    # the source case's file naming.
    steps = [(timestep_index(p.name), p) for p in pvtus]
    steps = [(i, p) for i, p in steps if i is not None]
    if steps:
        steps.sort()
        rec["first_step"], rec["last_step"] = steps[0][0], steps[-1][0]
        last = steps[-1][1]
    else:
        last = pvtus[-1]
        rec["first_step"] = rec["last_step"] = ""
    rec["last_pvtu"] = str(last.relative_to(case_dir))

    # Record a prefix mismatch as provenance, not as a fault.
    pvtu_prefix = re.sub(r"_\d+$", "", Path(rec.get("last_pvtu", last.name)).stem)
    pvtu_prefix = Path(pvtu_prefix).name
    rec["pvtu_prefix"] = pvtu_prefix
    rec["copied_from"] = pvtu_prefix if pvtu_prefix != rec["case"] else ""

    if quick:
        rec["status"] = "not-checked"
        return rec

    fields = pvtu_fields(last)
    rec["fields"] = "|".join(fields)
    missing = [f for f in REQUIRED_FIELDS if f not in fields]
    rec["missing_fields"] = "|".join(missing)
    rec["usable"] = int(not missing)
    rec["status"] = "ok" if not missing else "missing-fields"

    if deep and not missing:
        rec.update(deep_probe(last))

    return rec


def deep_probe(pvtu: Path) -> dict:
    """Open the last PVTU with VTK: mesh size, NaNs, value ranges."""
    out = {}
    try:
        import vtk
        from vtk.util.numpy_support import vtk_to_numpy
        import numpy as np
    except ImportError:
        out["deep_error"] = "vtk/numpy unavailable"
        return out

    try:
        rdr = vtk.vtkXMLPUnstructuredGridReader()
        rdr.SetFileName(str(pvtu))
        rdr.Update()
        grid = rdr.GetOutput()
        n_pts = grid.GetNumberOfPoints()
        if n_pts == 0:
            out["deep_error"] = "no points"
            return out
        out["n_nodes"] = n_pts
        out["n_cells"] = grid.GetNumberOfCells()
        out["cell_type"] = grid.GetCellType(0)
        out["is_tetra"] = int(grid.GetCellType(0) == 10)

        pts = vtk_to_numpy(grid.GetPoints().GetData())
        out["bbox_mm"] = " ".join(
            f"{v*1000:.1f}" for v in
            list(pts.min(axis=0)) + list(pts.max(axis=0))
        )

        pd = grid.GetPointData()
        bad = 0
        for name in REQUIRED_FIELDS:
            arr = pd.GetArray(name)
            if arr is None:
                continue
            a = vtk_to_numpy(arr)
            bad += int(np.isnan(a).sum() + np.isinf(a).sum())
            if name == "Temperature":
                out["T_max_C"] = round(float(a.max()), 1)
            elif name == "Pressure":
                out["P_absmax_MPa"] = round(float(np.abs(a).max()) / 1e6, 1)
            elif name == "Displacement":
                out["u_max"] = round(float(np.linalg.norm(a, axis=1).max()), 4)
            elif name == "LEVEL":
                out["n_inside_tool"] = int((a < 0).sum())
        out["n_nan_inf"] = bad
        out["healthy"] = int(bad == 0 and out.get("is_tetra", 0) == 1)
    except Exception as exc:                        # noqa: BLE001
        out["deep_error"] = f"{type(exc).__name__}: {exc}"
    return out


def find_cases(root: Path, max_depth: int = 3):
    """Find *.gid directories under root, breadth-first, bounded depth."""
    found = []
    stack = [(root, 0)]
    while stack:
        d, depth = stack.pop(0)
        try:
            entries = sorted(d.iterdir())
        except OSError:
            continue
        for e in entries:
            if not e.is_dir():
                continue
            if e.name.endswith(".gid"):
                found.append(e)
            elif depth < max_depth:
                stack.append((e, depth + 1))
    return found


COLUMNS = [
    "family", "case", "status", "usable", "healthy",
    "pin_geometry", "tilt_deg", "rotation_signed", "rotation_text",
    "advancing_mm_min", "plate_height", "revolutions", "steps_per_rev",
    "n_steps", "dt", "n_pvtu", "first_step", "last_step",
    "has_run_jaxtrace", "vel_start", "vel_end", "vel_n_steps", "rk4_n_steps",
    "mesh_pattern", "mesh_subdir",
    "n_nodes", "n_cells", "is_tetra", "n_nan_inf", "T_max_C",
    "P_absmax_MPa", "u_max", "n_inside_tool",
    "som_rpm", "som_tilt_deg", "som_plunge", "som_vert_load",
    "som_tool", "som_tool_angle0", "som_time_step", "som_time_interval",
    "som_travelling_bc", "som_frame_ref", "som_friction",
    "fix_n_rows", "fix_n_nonzero",
    "fix_vx_max", "fix_vy_max", "fix_vz_max",
    "fix_vx_median", "fix_vy_median", "fix_vz_median",
    "n_stages", "n_stages_with_som", "data_layout", "stages", "stage_used", "som_file",
    "info_som_disagree", "data_note",
    "material", "has_norton", "friction_model",
    "file_prefix", "prefix_matches_folder", "pvtu_prefix", "copied_from",
    "post_dir", "last_pvtu",
    "missing_fields", "fields", "bbox_mm", "path",
    "stage_files", "scan_error", "deep_error", "som_error", "data_error",
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", required=True, type=Path,
                    help="folder containing the case families (READ-ONLY)")
    ap.add_argument("--out", type=Path, default=Path("."),
                    help="where to write the report (NOT under --root)")
    ap.add_argument("--quick", action="store_true",
                    help="structure + parameters only; no PVTU reads")
    ap.add_argument("--deep", action="store_true",
                    help="also open the last PVTU with VTK (slower, richer)")
    ap.add_argument("--max-depth", type=int, default=3)
    args = ap.parse_args()

    root = args.root.resolve()
    if not root.is_dir():
        print(f"ERROR: --root not found: {root}", file=sys.stderr)
        return 1

    out_dir = args.out.resolve()
    # Refuse to write inside the surveyed tree.
    if out_dir == root or str(out_dir).startswith(str(root) + os.sep):
        print(f"ERROR: --out is inside --root; the survey must not write there.",
              file=sys.stderr)
        return 1
    out_dir.mkdir(parents=True, exist_ok=True)

    print(f"surveying {root}")
    print(f"  mode: {'quick' if args.quick else ('deep' if args.deep else 'normal')}")
    t0 = time.time()

    cases = find_cases(root, args.max_depth)
    print(f"  found {len(cases)} .gid folders in {time.time()-t0:.1f}s")

    records = []
    for i, c in enumerate(cases, 1):
        t1 = time.time()
        rec = survey_case(c, args.quick, args.deep)
        records.append(rec)
        print(f"  [{i:3d}/{len(cases)}] {rec['family']}/{rec['case']:12s} "
              f"{rec.get('status','?'):14s} "
              f"pin={rec.get('pin_geometry','?'):12.12s} "
              f"tilt={rec.get('tilt_deg','?'):>5.5s} "
              f"n_pvtu={rec.get('n_pvtu',0):<5d} ({time.time()-t1:.1f}s)",
              flush=True)

    csv_path = out_dir / "case_survey.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=COLUMNS, extrasaction="ignore")
        w.writeheader()
        for r in records:
            w.writerow(r)

    md_path = out_dir / "case_survey.md"
    write_markdown(md_path, root, records, args)

    print()
    print(f"  wrote {csv_path}")
    print(f"  wrote {md_path}")
    print(f"  total {time.time()-t0:.1f}s")
    return 0


def write_markdown(path: Path, root: Path, records: list, args) -> None:
    lines = [
        "# FSW case survey",
        "",
        f"Root: `{root}`  (read-only)",
        f"Generated: {time.strftime('%Y-%m-%d %H:%M')}  "
        f"· mode: {'quick' if args.quick else ('deep' if args.deep else 'normal')}",
        f"Cases found: **{len(records)}**",
        "",
    ]

    usable = [r for r in records if r.get("usable") == 1]
    if not args.quick:
        lines += [f"Usable (all four required fields present): "
                  f"**{len(usable)} / {len(records)}**", ""]

    # Group by family
    fams = {}
    for r in records:
        fams.setdefault(r["family"], []).append(r)

    lines += ["## By family", ""]
    for fam in sorted(fams):
        rs = fams[fam]
        lines += [f"### {fam}  ({len(rs)} cases)", ""]
        lines += ["| case | pin | tilt | ω signed | v (mm/min) | steps/rev | n_pvtu | last | status |",
                  "|---|---|---|---|---|---|---|---|---|"]
        for r in sorted(rs, key=lambda x: x["case"]):
            lines.append(
                f"| `{r['case']}` | {r.get('pin_geometry','?')} | "
                f"{r.get('tilt_deg','?')} | {r.get('rotation_signed','?')} | "
                f"{r.get('advancing_mm_min','?')} | {r.get('steps_per_rev','?')} | "
                f"{r.get('n_pvtu',0)} | {r.get('last_step','?')} | "
                f"{r.get('status','?')} |"
            )
        lines.append("")

    # Things worth knowing before using any of these
    notes = []
    tilted = [r for r in records
              if _f(r.get("tilt_deg")) not in (None, 0.0)]
    if tilted:
        notes.append(
            f"**{len(tilted)} case(s) have a non-zero tilt angle** "
            f"({', '.join(r['case'] for r in tilted[:8])}"
            f"{'…' if len(tilted) > 8 else ''}). A tilted tool is NOT "
            "axisymmetric about the vertical, so its tool-frame field is "
            "periodic at ω, not steady — load a full revolution, not a single "
            "step."
        )
    ccw = [r for r in records if _f(r.get("rotation_signed")) and _f(r.get("rotation_signed")) > 0]
    if ccw:
        notes.append(
            f"**{len(ccw)} case(s) rotate counter-clockwise** (signed ω > 0): "
            f"{', '.join(r['case'] for r in ccw[:8])}"
            f"{'…' if len(ccw) > 8 else ''}. Their advancing side is mirrored; "
            "orientation must be detected per case, not assumed."
        )
    noncyl = [r for r in records
              if r.get("pin_geometry") and "CYLINDRIC" not in r["pin_geometry"].upper()]
    if noncyl:
        notes.append(
            f"**{len(noncyl)} case(s) have a non-cylindrical pin** "
            f"(threaded/fluted/flats/conical). These break axisymmetry, so the "
            "field is periodic at ω — load a full revolution."
        )
    mism = [r for r in records
            if (r.get("prefix_matches_folder") == 0 and r.get("file_prefix"))
            or r.get("copied_from")]
    if mism:
        pairs = []
        for r in mism[:8]:
            src = r.get("copied_from") or r.get("file_prefix")
            pairs.append(f"{r['case']}←{src}")
        notes.append(
            f"**{len(mism)} case(s) were COPIED from another case**, renamed and "
            f"re-run with changed parameters: {', '.join(pairs)}"
            f"{'…' if len(mism) > 8 else ''}. The inner files keep the source "
            "case's prefix (e.g. `D4.gid` holding `C2_*.pvtu`), but they are "
            "that case's own output and carry ITS parameters. Do not filter on "
            "the folder name, and read parameters from `data/*.som.dat`, not "
            "from a stale `.info`."
        )
    periodic = [r for r in records
                if (r.get("pin_geometry") and "CYLINDRIC" not in r["pin_geometry"].upper())
                or _f(r.get("som_tilt_deg")) not in (None, 0.0)]
    with_window = [r for r in periodic if r.get("vel_n_steps")]
    if with_window:
        ranges = sorted({f"{r.get('vel_start')}-{r.get('vel_end')}" for r in with_window})
        notes.append(
            f"**{len(with_window)} periodic case(s) declare a full-revolution "
            f"window** in their `run_jaxtrace.sh` (`VEL_START`..`VEL_END`): "
            f"{', '.join(ranges)}. Use that range for phase-resolved damage; a "
            "single last-step snapshot is one arbitrary rotational phase."
        )

    bad = [r for r in records if r.get("status") not in ("ok", "not-checked")]
    if bad:
        notes.append(
            f"**{len(bad)} case(s) are not directly usable**: "
            + ", ".join(f"`{r['case']}` ({r.get('status')})" for r in bad[:10])
            + ("…" if len(bad) > 10 else "")
        )

    if notes:
        lines += ["## Notes", ""] + [f"- {n}" for n in notes] + [""]

    lines += [
        "## Columns in `case_survey.csv`",
        "",
        "`status` — ok | missing-fields | no-post | no-pvtu | not-checked",
        "`usable` — all of " + ", ".join(f"`{f}`" for f in REQUIRED_FIELDS) + " present",
        "`healthy` — deep mode only: tetrahedral and no NaN/Inf",
        "",
    ]
    path.write_text("\n".join(lines))


def _f(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


if __name__ == "__main__":
    raise SystemExit(main())
