"""
build_grid_velocity_case.py --- bake a per-case grid velocity module.

Reads a source velocity field (analytic module OR mesh PVTU with a
Displacement field), samples it onto a uniform Cartesian grid, and
writes a concrete instance of grid_velocity_field.py alongside the case.

The generated module can then be handed to run_tracking.py directly:

    python run_tracking.py --velocity-source analytic \\
        --velocity-module <case>/grid_velocity_<case>.py \\
        --domain-bbox <the grid's bbox> \\
        --precision float32 \\
        --seed-source grid --seed-box ... --seed-grid ... \\
        --n-steps 6000 --dt 5e-5 \\
        --output <out_dir>

Because the module registers itself as an AnalyticVelocityProvider,
run_tracking.py skips the octree + element-search code path entirely.
Each RK4 sub-stage is one O(1) grid lookup per particle.

Example (recirc_2026 uniform base grid):

    python scripts/build_grid_velocity_case.py \\
        --source analytic \\
        --source-module /scratch/shared/ROM/FOM_analytic/recirc_2026/recirculation_field.py \\
        --bbox -0.0625 0.0625 -0.03125 0.03125 -0.015625 0.015625 \\
        --n-cells 64 32 8 \\
        --out /scratch/shared/ROM/FOM_analytic/recirc_2026/grid_velocity_recirc_uniform.py

Example (rot_cyl_2026 sampling from the 4-lvl mesh):

    python scripts/build_grid_velocity_case.py \\
        --source mesh \\
        --source-pvtu /scratch/shared/ROM/FOM_analytic/rot_cyl_2026/mesh_4lvl/mesh_0.pvtu \\
        --bbox -0.25 0.25 -0.125 0.125 -0.015625 0.015625 \\
        --n-cells 128 64 8 \\
        --out /scratch/shared/ROM/FOM_analytic/rot_cyl_2026/grid_velocity_rot_cyl_uniform.py
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
import textwrap
from pathlib import Path

# Ensure the local jaxtrace package is importable when running from a
# checkout (source-analytic modules may `from jaxtrace...` at import).
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import numpy as np
import vtk
from vtk.util.numpy_support import numpy_to_vtk, vtk_to_numpy


TEMPLATE = '''\
"""Auto-generated grid velocity module for {case_label}.
Generated by scripts/build_grid_velocity_case.py.

Do NOT edit by hand -- rerun the generator with different parameters.
Source: {source_desc}
Grid:   {n_cells} cells over {bbox}
Interp: {interp}

Loading this module registers itself as an AnalyticVelocityProvider,
so run_tracking.py --velocity-source analytic skips all mesh/octree
code and does one O(1) grid lookup per RK4 sub-stage.
"""

import numpy as np
import jax.numpy as jnp
from jaxtrace.gpu.tracking.velocity_provider import AnalyticVelocityProvider


# --- Baked-in grid ---------------------------------------------------------

GRID_XMIN = ({xmin[0]!r}, {xmin[1]!r}, {xmin[2]!r})
GRID_XMAX = ({xmax[0]!r}, {xmax[1]!r}, {xmax[2]!r})
GRID_N    = ({n[0]},  {n[1]},  {n[2]})
INTERP_MODE = "{interp}"

# Velocity values stored as a .npz sibling (loaded at import).
_GRID_V_NPZ = "{npz_name}"


def _load_grid_v():
    from pathlib import Path
    here = Path(__file__).resolve().parent
    return np.load(here / _GRID_V_NPZ)["v"]


_GRID_V = _load_grid_v()

_XMIN = jnp.asarray(GRID_XMIN, dtype=jnp.float32)
_XMAX = jnp.asarray(GRID_XMAX, dtype=jnp.float32)
_N    = jnp.asarray(GRID_N,    dtype=jnp.int32)
_DX   = (_XMAX - _XMIN) / _N.astype(jnp.float32)
_V    = jnp.asarray(_GRID_V.reshape(GRID_N[0], GRID_N[1], GRID_N[2], 3)
                    .astype(np.float32))


def _clamp(idx, n):
    return jnp.clip(idx, 0, n - 1)


def _velocity_fn_nearest(pos):
    frac = (pos - _XMIN) / _DX
    idx = jnp.floor(frac).astype(jnp.int32)
    return _V[_clamp(idx[0], _N[0]), _clamp(idx[1], _N[1]),
              _clamp(idx[2], _N[2])]


def _velocity_fn_trilinear(pos):
    frac = (pos - _XMIN) / _DX - 0.5
    i0 = jnp.floor(frac).astype(jnp.int32)
    t = frac - i0.astype(jnp.float32)
    i1 = i0 + 1
    ix0 = _clamp(i0[0], _N[0]); ix1 = _clamp(i1[0], _N[0])
    iy0 = _clamp(i0[1], _N[1]); iy1 = _clamp(i1[1], _N[1])
    iz0 = _clamp(i0[2], _N[2]); iz1 = _clamp(i1[2], _N[2])
    tx, ty, tz = t[0], t[1], t[2]
    c000 = _V[ix0, iy0, iz0]; c100 = _V[ix1, iy0, iz0]
    c010 = _V[ix0, iy1, iz0]; c110 = _V[ix1, iy1, iz0]
    c001 = _V[ix0, iy0, iz1]; c101 = _V[ix1, iy0, iz1]
    c011 = _V[ix0, iy1, iz1]; c111 = _V[ix1, iy1, iz1]
    c00 = c000 * (1 - tx) + c100 * tx
    c10 = c010 * (1 - tx) + c110 * tx
    c01 = c001 * (1 - tx) + c101 * tx
    c11 = c011 * (1 - tx) + c111 * tx
    c0 = c00 * (1 - ty) + c10 * ty
    c1 = c01 * (1 - ty) + c11 * ty
    return c0 * (1 - tz) + c1 * tz


def velocity_fn(pos):
    if INTERP_MODE == "nearest":
        return _velocity_fn_nearest(pos)
    return _velocity_fn_trilinear(pos)


DOMAIN_BBOX = (
    (float(GRID_XMIN[0]), float(GRID_XMAX[0])),
    (float(GRID_XMIN[1]), float(GRID_XMAX[1])),
    (float(GRID_XMIN[2]), float(GRID_XMAX[2])),
)


def build_provider(domain_bbox=None, dt=0.0, t_start=0.0):
    del dt, t_start
    if domain_bbox is None:
        domain_bbox = DOMAIN_BBOX
    return AnalyticVelocityProvider(
        velocity_fn=velocity_fn,
        is_time_dependent=False,
        level_set_fn=None,
        domain_bbox=domain_bbox,
        meta={{
            "name":        "{case_label}",
            "source":      "{source_desc}",
            "grid_xmin":   GRID_XMIN,
            "grid_xmax":   GRID_XMAX,
            "grid_n":      GRID_N,
            "interp_mode": INTERP_MODE,
            "n_cells":     int(np.prod(GRID_N)),
            "note":        "O(1) grid lookup; no element search, no octree.",
        }},
    )
'''


def load_module(path: Path):
    spec = importlib.util.spec_from_file_location("case_field", str(path))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def sample_from_analytic(module_path: Path, points_xyz: np.ndarray) -> np.ndarray:
    import jax
    import jax.numpy as jnp
    mod = load_module(module_path)
    vfn_v = jax.vmap(mod.velocity_fn)
    return np.asarray(vfn_v(jnp.asarray(points_xyz)))


def sample_from_mesh(pvtu_path: Path, points_xyz: np.ndarray) -> np.ndarray:
    if pvtu_path.suffix == ".pvtu":
        r = vtk.vtkXMLPUnstructuredGridReader()
    else:
        r = vtk.vtkXMLUnstructuredGridReader()
    r.SetFileName(str(pvtu_path))
    r.Update()
    ug = r.GetOutput()
    probe_pts = vtk.vtkPoints()
    probe_pts.SetData(numpy_to_vtk(points_xyz.astype(np.float64), deep=True))
    probe_poly = vtk.vtkPolyData()
    probe_poly.SetPoints(probe_pts)
    probe = vtk.vtkProbeFilter()
    probe.SetInputData(probe_poly)
    probe.SetSourceData(ug)
    probe.Update()
    out = probe.GetOutput()
    v = vtk_to_numpy(out.GetPointData().GetArray("Displacement"))
    return v.astype(np.float64)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", choices=["analytic", "mesh"], required=True)
    ap.add_argument("--source-module", type=Path,
                    help="For --source analytic")
    ap.add_argument("--source-pvtu", type=Path,
                    help="For --source mesh")
    ap.add_argument("--bbox", type=float, nargs=6, required=True,
                    metavar=("XMIN", "XMAX", "YMIN", "YMAX", "ZMIN", "ZMAX"))
    ap.add_argument("--n-cells", type=int, nargs=3, required=True)
    ap.add_argument("--interp", choices=["trilinear", "nearest"],
                    default="trilinear")
    ap.add_argument("--out", type=Path, required=True,
                    help="Path to the generated .py module.  The values "
                         "array is written to <out_stem>.npz alongside.")
    args = ap.parse_args()

    xmin = np.array([args.bbox[0], args.bbox[2], args.bbox[4]])
    xmax = np.array([args.bbox[1], args.bbox[3], args.bbox[5]])
    nx, ny, nz = args.n_cells
    dx = (xmax - xmin) / np.array([nx, ny, nz], dtype=np.float64)

    # Cell centres.
    xs = xmin[0] + (np.arange(nx) + 0.5) * dx[0]
    ys = xmin[1] + (np.arange(ny) + 0.5) * dx[1]
    zs = xmin[2] + (np.arange(nz) + 0.5) * dx[2]
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
    pts = np.column_stack([X.ravel(), Y.ravel(), Z.ravel()])

    if args.source == "analytic":
        if args.source_module is None:
            raise SystemExit("--source analytic requires --source-module")
        v = sample_from_analytic(args.source_module, pts)
        source_desc = f"analytic:{args.source_module.name}"
    else:
        if args.source_pvtu is None:
            raise SystemExit("--source mesh requires --source-pvtu")
        v = sample_from_mesh(args.source_pvtu, pts)
        source_desc = f"mesh:{args.source_pvtu.name}"

    args.out.parent.mkdir(parents=True, exist_ok=True)
    npz_path = args.out.with_suffix(".npz")
    np.savez_compressed(npz_path, v=v.astype(np.float32))
    print(f"wrote {npz_path}  ({v.nbytes//1024} KiB)")

    src = TEMPLATE.format(
        case_label=args.out.stem,
        source_desc=source_desc,
        bbox=list(args.bbox),
        n_cells=list(args.n_cells),
        interp=args.interp,
        xmin=xmin.tolist(),
        xmax=xmax.tolist(),
        n=list(args.n_cells),
        npz_name=npz_path.name,
    )
    args.out.write_text(src)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
