"""
build_hier_grid_velocity_case.py --- bake a per-case *hierarchical*
grid velocity module.

Companion to `build_grid_velocity_case.py` (uniform only).  This tool
handles **block-refined** Cartesian grids: a small list of uniform
Cartesian bricks, finest-first, sharing the same origin.  Every query
walks the block list in order and picks the first block containing the
query point.

The generated module registers itself as an
`AnalyticVelocityProvider`, so `run_tracking.py --velocity-source
analytic --velocity-module <module.py>` skips all mesh/octree code and
runs one hierarchical lookup per RK4 substage.

Runtime cost per substage: O(N_blocks) point-in-box tests + one O(1)
trilinear interpolation in the winning block.  For N_blocks <= 3 the
cost is essentially unchanged from the uniform-grid case.

Design choice for storage: each block's velocity is baked into a
single `.npz` file keyed by block index, alongside a small manifest
of block metadata (xmin, xmax, n_cells).  The generated `.py` module
loads the npz at import time and constructs JAX arrays.

Also emits a `.vtu` geometry file per block (hex cells, coloured by
|v|) so the grid can be visualised in ParaView.  Combine the blocks
with ParaView's "Group Datasets" filter, or open the multi-block
wrapper `.vtm` file we also emit.

Example (recirc_2026 4-lvl block-refined grid):

    python scripts/build_hier_grid_velocity_case.py \\
        --source analytic \\
        --source-module /scratch/shared/ROM/FOM_analytic/recirc_2026/recirculation_field.py \\
        --bbox   -0.0625 0.0625 -0.03125 0.03125 -0.015625 0.015625 \\
        --base-n 64 32 8 \\
        --grid-type 4lvl \\
        --refine-r1 0.03125 --refine-r2 0.015625 \\
        --out /scratch/shared/ROM/FOM_analytic/recirc_2026/grid_velocity_recirc_4lvl.py
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

import numpy as np
import vtk
from vtk.util.numpy_support import numpy_to_vtk, numpy_to_vtkIdTypeArray, vtk_to_numpy


# ---------------------------------------------------------------------------
# Module template (baked with hardcoded block metadata + npz filename).
# ---------------------------------------------------------------------------

TEMPLATE = '''\
"""Auto-generated **hierarchical grid** velocity module for {case_label}.
Generated by scripts/build_hier_grid_velocity_case.py.

Source: {source_desc}
Grid:   {n_blocks} block(s), finest-first
{block_summary_indented}
Interp: {interp}

Loading this module registers as an AnalyticVelocityProvider, so
run_tracking.py --velocity-source analytic performs no mesh/octree work.
Runtime cost per RK4 sub-stage: {n_blocks} point-in-box tests + one
trilinear interpolation in the winning block.
"""

import numpy as np
import jax
import jax.numpy as jnp
from jaxtrace.gpu.tracking.velocity_provider import AnalyticVelocityProvider


# --- Baked block table ------------------------------------------------------

# BLOCK_META rows are (xmin_xyz, xmax_xyz, n_cells_xyz) in finest-first order.
BLOCK_META = [
{block_meta_repr}
]
INTERP_MODE = "{interp}"

_GRID_NPZ = "{npz_name}"


def _load_blocks():
    """Load per-block velocity arrays from the sibling npz file."""
    from pathlib import Path
    here = Path(__file__).resolve().parent
    z = np.load(here / _GRID_NPZ)
    # keys are v_0, v_1, ...
    return [z[f"v_{{i}}"].reshape(*BLOCK_META[i][2], 3).astype(np.float32)
            for i in range(len(BLOCK_META))]


_BLOCK_V_NP = _load_blocks()

# JAX-side constants (per block)
_XMIN = jnp.asarray(
    np.array([b[0] for b in BLOCK_META], dtype=np.float32))    # (K, 3)
_XMAX = jnp.asarray(
    np.array([b[1] for b in BLOCK_META], dtype=np.float32))
_N    = jnp.asarray(
    np.array([b[2] for b in BLOCK_META], dtype=np.int32))
_DX   = (_XMAX - _XMIN) / _N.astype(jnp.float32)
_V    = [jnp.asarray(v) for v in _BLOCK_V_NP]


def _clamp(idx, n):
    return jnp.clip(idx, 0, n - 1)


def _inside_block(pos, k):
    return jnp.all((pos >= _XMIN[k]) & (pos < _XMAX[k]))


def _trilinear_block(pos, k):
    """Trilinear (C0) lookup inside block k -- 8-corner linear interp."""
    frac = (pos - _XMIN[k]) / _DX[k] - 0.5
    i0 = jnp.floor(frac).astype(jnp.int32)
    t = frac - i0.astype(jnp.float32)
    i1 = i0 + 1
    n = _N[k]
    ix0 = _clamp(i0[0], n[0]); ix1 = _clamp(i1[0], n[0])
    iy0 = _clamp(i0[1], n[1]); iy1 = _clamp(i1[1], n[1])
    iz0 = _clamp(i0[2], n[2]); iz1 = _clamp(i1[2], n[2])
    tx, ty, tz = t[0], t[1], t[2]
    V = _V[k]
    c000 = V[ix0, iy0, iz0]; c100 = V[ix1, iy0, iz0]
    c010 = V[ix0, iy1, iz0]; c110 = V[ix1, iy1, iz0]
    c001 = V[ix0, iy0, iz1]; c101 = V[ix1, iy0, iz1]
    c011 = V[ix0, iy1, iz1]; c111 = V[ix1, iy1, iz1]
    c00 = c000 * (1 - tx) + c100 * tx
    c10 = c010 * (1 - tx) + c110 * tx
    c01 = c001 * (1 - tx) + c101 * tx
    c11 = c011 * (1 - tx) + c111 * tx
    c0 = c00 * (1 - ty) + c10 * ty
    c1 = c01 * (1 - ty) + c11 * ty
    return c0 * (1 - tz) + c1 * tz


def _catmull_rom_weights(t):
    """1D Catmull-Rom cubic basis at fractional position t in [0, 1].
    Returns (w_{{-1}}, w_{{0}}, w_{{1}}, w_{{2}}) weights for the 4-point stencil."""
    t2 = t * t
    t3 = t2 * t
    w_m1 = -0.5 * t3 +       t2 - 0.5 * t
    w_0  =  1.5 * t3 - 2.5 * t2       + 1.0
    w_p1 = -1.5 * t3 + 2.0 * t2 + 0.5 * t
    w_p2 =  0.5 * t3 - 0.5 * t2
    return w_m1, w_0, w_p1, w_p2


def _tricubic_block(pos, k):
    """Tricubic Catmull-Rom (cardinal cubic) lookup inside block k.

    C^1 continuous, exact for cubic polynomials, no gradient input
    needed.  Reads a 4x4x4 stencil per query.  Local -- no global
    convolution / no basis matrix inversion.
    """
    frac = (pos - _XMIN[k]) / _DX[k] - 0.5
    i0 = jnp.floor(frac).astype(jnp.int32)
    t = frac - i0.astype(jnp.float32)
    n = _N[k]
    V = _V[k]
    # 1D weights per axis
    wx_m1, wx_0, wx_p1, wx_p2 = _catmull_rom_weights(t[0])
    wy_m1, wy_0, wy_p1, wy_p2 = _catmull_rom_weights(t[1])
    wz_m1, wz_0, wz_p1, wz_p2 = _catmull_rom_weights(t[2])
    wxs = jnp.stack([wx_m1, wx_0, wx_p1, wx_p2])   # (4,)
    wys = jnp.stack([wy_m1, wy_0, wy_p1, wy_p2])
    wzs = jnp.stack([wz_m1, wz_0, wz_p1, wz_p2])
    # 4x4x4 sample indices around i0
    ixs = jnp.stack([_clamp(i0[0] + o, n[0]) for o in (-1, 0, 1, 2)])
    iys = jnp.stack([_clamp(i0[1] + o, n[1]) for o in (-1, 0, 1, 2)])
    izs = jnp.stack([_clamp(i0[2] + o, n[2]) for o in (-1, 0, 1, 2)])
    # accumulate
    acc = jnp.zeros(3, dtype=V.dtype)
    for a in range(4):
        for b in range(4):
            for c in range(4):
                w = wxs[a] * wys[b] * wzs[c]
                acc = acc + w * V[ixs[a], iys[b], izs[c]]
    return acc


def _block_lookup(pos, k):
    """Dispatch on INTERP_MODE for the block-k lookup."""
    if INTERP_MODE == "nearest":
        return _nearest_block(pos, k)
    if INTERP_MODE == "tricubic":
        return _tricubic_block(pos, k)
    return _trilinear_block(pos, k)


def _nearest_block(pos, k):
    """Nearest-cell (0th-order) lookup inside block k."""
    frac = (pos - _XMIN[k]) / _DX[k]
    idx = jnp.floor(frac).astype(jnp.int32)
    n = _N[k]
    return _V[k][_clamp(idx[0], n[0]), _clamp(idx[1], n[1]), _clamp(idx[2], n[2])]


def velocity_fn(pos):
    """Hierarchical lookup: finest block first.  Falls back to the last
    (coarsest / base) block if the query lies inside no finer block —
    the base block is guaranteed to cover the whole domain.  Interpolation
    inside each block is controlled by INTERP_MODE
    (trilinear | tricubic | nearest)."""
{velocity_dispatch}


DOMAIN_BBOX = (
    (float(BLOCK_META[-1][0][0]), float(BLOCK_META[-1][1][0])),
    (float(BLOCK_META[-1][0][1]), float(BLOCK_META[-1][1][1])),
    (float(BLOCK_META[-1][0][2]), float(BLOCK_META[-1][1][2])),
)


def build_provider(domain_bbox=None, dt=0.0, t_start=0.0):
    del dt, t_start
    if domain_bbox is None:
        domain_bbox = DOMAIN_BBOX
    return AnalyticVelocityProvider(
        velocity_fn=velocity_fn,
        is_time_dependent=False,
        level_set_fn=None,
        domain_bbox=domain_bbox,
        meta={{
            "name":        "{case_label}",
            "source":      "{source_desc}",
            "n_blocks":    len(BLOCK_META),
            "block_shape_finest_first":
                [tuple(b[2]) for b in BLOCK_META],
            "interp_mode": INTERP_MODE,
            "note":        "Hierarchical grid: {n_blocks} block(s), "
                           "finest-first. O(K) point-in-box + O(1) "
                           "trilinear interp per query.",
        }},
    )
'''


# The dispatch is generated inline: we use jnp.where cascades so the
# whole function is JAX-jittable + differentiable with no control flow.
def _make_velocity_dispatch(n_blocks: int) -> str:
    """Emit a jax.lax.cond-free dispatch: fold from coarsest to finest,
    overwriting the result whenever a finer block claims the point.
    Uses ``_block_lookup`` which dispatches on INTERP_MODE at import
    time (single Python if -- no jax control flow needed).
    """
    lines = [
        "    # start from the coarsest (last) block, which covers the whole domain",
        f"    result = _block_lookup(pos, {n_blocks - 1})",
    ]
    for k in range(n_blocks - 2, -1, -1):
        lines += [
            f"    v_{k} = _block_lookup(pos, {k})",
            f"    inside_{k} = _inside_block(pos, {k})",
            f"    result = jnp.where(inside_{k}, v_{k}, result)",
        ]
    lines.append("    return result")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Hierarchical grid construction
# ---------------------------------------------------------------------------

def make_malmo_aligned_hier_grid(source_pvtu: Path,
                                 bbox: tuple[float, ...],
                                 leaf_capacity: int = 256,
                                 max_depths: int | None = None,
                                 cells_per_edge: int = 1,
                                 verbose: bool = False) -> list[dict]:
    """Build a hierarchical grid aligned with the FOM's MALMO octree.

    Runs the same `build_global_morton_octree` used by the tracker on the
    source PVTU's mesh, then per-depth:
      * computes a bounding box that encloses all leaves at THAT depth
        (and everything finer -- since deeper leaves lie inside the
        coarser cube they refine, taking bbox of all leaves at depth
        >= d gives us the 'volume the mesh refines at least to level d')
      * sets grid cell size = MALMO cube edge / cells_per_edge.

    Returns finest-first list of block dicts.

    ``max_depths`` optionally caps how deep we go (e.g. 4 -> use only
    depths 2..4).  ``cells_per_edge = 1`` matches MALMO cube exactly.
    """
    # Load mesh
    reader = (vtk.vtkXMLPUnstructuredGridReader()
              if source_pvtu.suffix == ".pvtu"
              else vtk.vtkXMLUnstructuredGridReader())
    reader.SetFileName(str(source_pvtu)); reader.Update()
    ug = reader.GetOutput()
    pts_mesh = vtk_to_numpy(ug.GetPoints().GetData()).astype(np.float32)
    n_cells_mesh = ug.GetNumberOfCells()
    conn = np.empty((n_cells_mesh, 4), dtype=np.int32)
    cell = vtk.vtkGenericCell()
    for i in range(n_cells_mesh):
        ug.GetCell(i, cell); ids = cell.GetPointIds()
        for j in range(4): conn[i, j] = ids.GetId(j)

    # Compute centroids
    centroids = pts_mesh[conn].mean(axis=1)

    # Import MALMO builders lazily
    from jaxtrace.gpu.search.morton_octree_builder import (
        build_global_morton_octree, build_adaptive_octree_leaves,
    )
    ms = build_global_morton_octree(
        pts_mesh, conn, leaf_capacity=leaf_capacity, verbose=False,
    )
    leaves, _ = build_adaptive_octree_leaves(
        ms.morton_sorted,
        np.arange(ms.morton_sorted.size, dtype=np.int32),
        leaf_capacity=leaf_capacity,
    )
    per_depth: dict[int, list] = {}
    for lf in leaves:
        d = lf.prefix_bits // 3
        per_depth.setdefault(d, []).append(lf)
    depths_sorted = sorted(per_depth.keys())
    if verbose:
        print(f"  MALMO depths used: {depths_sorted}")

    # bbox from the CLI (should be mesh bbox with tiny epsilon)
    xmin_full = np.array([bbox[0], bbox[2], bbox[4]], dtype=np.float64)
    xmax_full = np.array([bbox[1], bbox[3], bbox[5]], dtype=np.float64)
    extent = ms.bbox_max.astype(np.float64) - ms.bbox_min.astype(np.float64)

    # For each depth d, we need the bounding box of the mesh region
    # that has at least that many refinement levels.  Since finer leaves
    # are always inside their coarser parent cube, "all cells at depth >= d"
    # is the right query.  We use the centroids of the leaves' member
    # elements to get the actual mesh region covered.
    blocks: list[dict] = []
    for d in depths_sorted:
        if max_depths is not None and d > max_depths:
            continue
        # collect all element ids in leaves at depth >= d
        elem_ids_here = []
        for lf in leaves:
            if lf.prefix_bits // 3 >= d:
                # these are element indices in morton_sorted order
                for idx in range(lf.start_idx, lf.start_idx + lf.length):
                    elem_ids_here.append(idx)
        elem_ids_here = np.asarray(elem_ids_here, dtype=np.int64)
        if elem_ids_here.size == 0:
            continue
        # actual element ids (unsorted)
        real_ids = np.arange(n_cells_mesh)[np.argsort(ms.morton_sorted)][elem_ids_here] \
            if hasattr(ms, "elem_ids_sorted") \
            else elem_ids_here
        # simpler + safer: use ms.elem_ids_sorted directly
        if hasattr(ms, "elem_ids_sorted"):
            real_ids = ms.elem_ids_sorted[elem_ids_here]
        # centroids of those elements
        cent = centroids[real_ids]
        cube_edge = extent / (2 ** d)
        # bbox = cent bbox +/- half a cube (to be safe about the leaf boundary)
        bmin = cent.min(axis=0) - 0.5 * cube_edge
        bmax = cent.max(axis=0) + 0.5 * cube_edge
        # clamp inside full mesh bbox
        bmin = np.maximum(bmin, xmin_full)
        bmax = np.minimum(bmax, xmax_full)
        # Compute per-axis n_cells so cell size ~ cube_edge / cells_per_edge
        target_dx = cube_edge / cells_per_edge
        n = np.maximum(2, np.round((bmax - bmin) / target_dx).astype(int))
        blocks.append(dict(xmin=bmin, xmax=bmax, n_cells=tuple(int(x) for x in n)))
        if verbose:
            n_cells_block = int(np.prod(n))
            print(f"    depth {d}: bbox x=[{bmin[0]:.3g},{bmax[0]:.3g}] "
                  f"y=[{bmin[1]:.3g},{bmax[1]:.3g}] "
                  f"z=[{bmin[2]:.3g},{bmax[2]:.3g}]  "
                  f"n={tuple(int(x) for x in n)}  cells={n_cells_block:,}")

    # Order finest-first: MALMO deepest depth = smallest cube = finest.
    blocks.reverse()
    return blocks


def make_hier_grid(bbox: tuple[float, ...],
                   base_n: tuple[int, int, int],
                   grid_type: str,
                   refine_r1: float,
                   refine_r2: float,
                   refine_r3: float = 0.0) -> list[dict]:
    """Return a finest-first list of block dicts (xmin, xmax, n_cells).

    grid_type ∈ {"uniform", "2lvl", "4lvl", "5lvl"}.  Refinement is
    always centred on the origin (matches recirc / rot_cyl / FSW
    cases).

    5lvl adds a third nested block for the 20-case cohort experiment:
      * base at (base_n)
      * inner1 at r <= refine_r1, 2 x base_n
      * inner2 at r <= refine_r2, 4 x base_n
      * inner3 at r <= refine_r3, 8 x base_n

    Intended for FSW where the pin-face shear-band at r ~= 21 mm
    drives PT error (Part 4 of the grid report), so users pick
    e.g. refine_r1=0.022, refine_r2=0.016, refine_r3=0.008.
    """
    xmin = np.array([bbox[0], bbox[2], bbox[4]], dtype=np.float64)
    xmax = np.array([bbox[1], bbox[3], bbox[5]], dtype=np.float64)
    base = dict(xmin=xmin.copy(), xmax=xmax.copy(),
                n_cells=tuple(base_n))
    if grid_type == "uniform":
        return [base]
    # 2-lvl: base + 2x-refined block within r ≤ refine_r1
    inner1 = dict(
        xmin=np.array([-refine_r1, -refine_r1, xmin[2]]),
        xmax=np.array([ refine_r1,  refine_r1, xmax[2]]),
        n_cells=(base_n[0] * 2, base_n[1] * 2, base_n[2] * 2),
    )
    if grid_type == "2lvl":
        return [inner1, base]
    # 4-lvl: base + 2x block + 4x block nested
    inner2 = dict(
        xmin=np.array([-refine_r2, -refine_r2, xmin[2]]),
        xmax=np.array([ refine_r2,  refine_r2, xmax[2]]),
        n_cells=(base_n[0] * 4, base_n[1] * 4, base_n[2] * 4),
    )
    if grid_type == "4lvl":
        return [inner2, inner1, base]
    # 5-lvl: base + 2x block + 3x block + 4x block nested.
    # The multipliers are capped at 4x (rather than the naive 8x) because
    # Part 4 of the grid report showed that refining past the underlying
    # finest tet edge (~140 um) gives no benefit under HCT.  4x base_n
    # = 360 xy cells at half-extent 8 mm gives Δx ~= 45 um.
    inner2b = dict(
        xmin=np.array([-refine_r2, -refine_r2, xmin[2]]),
        xmax=np.array([ refine_r2,  refine_r2, xmax[2]]),
        n_cells=(base_n[0] * 3, base_n[1] * 3, base_n[2] * 3),
    )
    inner3 = dict(
        xmin=np.array([-refine_r3, -refine_r3, xmin[2]]),
        xmax=np.array([ refine_r3,  refine_r3, xmax[2]]),
        n_cells=(base_n[0] * 4, base_n[1] * 4, base_n[2] * 4),
    )
    if grid_type == "5lvl":
        return [inner3, inner2b, inner1, base]
    raise ValueError(f"unknown grid_type: {grid_type}")


# ---------------------------------------------------------------------------
# Sampling
# ---------------------------------------------------------------------------

def sample_from_analytic(module_path: Path, points_xyz: np.ndarray) -> np.ndarray:
    import jax
    import jax.numpy as jnp
    spec = importlib.util.spec_from_file_location("_case", str(module_path))
    mod = importlib.util.module_from_spec(spec); spec.loader.exec_module(mod)
    vfn_v = jax.vmap(mod.velocity_fn)
    return np.asarray(vfn_v(jnp.asarray(points_xyz)))


def build_hct_projector(pvtu_path: Path, field_name: str = "Displacement",
                        cache_path: Path | None = None,
                        verbose: bool = True) -> dict:
    """Build (or load) the per-mesh HCT-3D state needed to evaluate
    the C1 Alfeld-split Bernstein cubic at arbitrary query points.

    Returns a dict with keys: `pts_mesh`, `conn`, `hct_coeffs`,
    `alfeld_centroids`, `ug` (a live vtkUnstructuredGrid for
    point-in-tet lookup via vtkCellLocator).

    If `cache_path` is given and exists, the SPR + HCT stage is
    loaded from the .npz there. If it does not exist, it is built
    and written. The mesh geometry and the case velocity are hashed
    into the cache filename so a mismatched cache is not silently
    reused.
    """
    reader = (vtk.vtkXMLPUnstructuredGridReader()
              if pvtu_path.suffix == ".pvtu"
              else vtk.vtkXMLUnstructuredGridReader())
    reader.SetFileName(str(pvtu_path)); reader.Update()
    ug = reader.GetOutput()

    pts_mesh = vtk_to_numpy(ug.GetPoints().GetData()).astype(np.float64)
    n_cells = ug.GetNumberOfCells()
    conn = np.empty((n_cells, 4), dtype=np.int64)
    cell = vtk.vtkGenericCell()
    for i in range(n_cells):
        ug.GetCell(i, cell)
        ids = cell.GetPointIds()
        for j in range(4):
            conn[i, j] = ids.GetId(j)
    v_nodal = vtk_to_numpy(
        ug.GetPointData().GetArray(field_name)).astype(np.float64)

    if cache_path is not None and cache_path.exists():
        if verbose:
            print(f"[hct-cache] loading {cache_path}")
        z = np.load(cache_path)
        hct_coeffs = z["hct_coeffs"]
        alfeld_centroids = z["alfeld_centroids"]
        # Sanity: cache must match this mesh + velocity.
        if (not np.array_equal(z["pts_mesh_hash"],
                               _hash_arr(pts_mesh))
                or not np.array_equal(z["v_nodal_hash"],
                                      _hash_arr(v_nodal))):
            raise SystemExit(f"[hct-cache] MISMATCH -- {cache_path} does "
                             f"not match this mesh + velocity. Delete "
                             f"the cache and rerun.")
    else:
        from jaxtrace.gpu.recovery.gradient_recovery import build_recovery
        from jaxtrace.gpu.recovery.hct3d import (
            build_alfeld_geometry, build_hct_bernstein_c1_taylor,
        )
        if verbose:
            print(f"[hct-cache] building SPR + Alfeld + HCT-3D coeffs "
                  f"for {n_cells:,} tets (this is the slow step)...")
        recovery = build_recovery(pts_mesh, conn, v_nodal,
                                  method="vertex_taylor", verbose=False)
        alfeld = build_alfeld_geometry(pts_mesh, conn, verbose=False)
        hct = build_hct_bernstein_c1_taylor(
            pts_mesh, conn, v_nodal,
            recovery.nodal_gradient,
            edge_grads=None,
            geom=alfeld, verbose=False,
        )
        hct_coeffs = hct.coeffs.astype(np.float32)
        alfeld_centroids = alfeld.centroids.astype(np.float64)
        if cache_path is not None:
            cache_path.parent.mkdir(parents=True, exist_ok=True)
            np.savez_compressed(
                cache_path,
                hct_coeffs=hct_coeffs,
                alfeld_centroids=alfeld_centroids,
                pts_mesh_hash=_hash_arr(pts_mesh),
                v_nodal_hash=_hash_arr(v_nodal),
            )
            if verbose:
                sz = cache_path.stat().st_size / (1024 * 1024)
                print(f"[hct-cache] wrote {cache_path} ({sz:.1f} MB)")

    return dict(pts_mesh=pts_mesh, conn=conn,
                hct_coeffs=hct_coeffs,
                alfeld_centroids=alfeld_centroids,
                ug=ug)


def _hash_arr(a: np.ndarray) -> np.ndarray:
    """Cheap fingerprint of an array (shape + first/last/mean bytes)."""
    import hashlib
    h = hashlib.sha1()
    h.update(np.asarray(a.shape, dtype=np.int64).tobytes())
    h.update(a.astype(np.float64, copy=False).tobytes())
    return np.frombuffer(h.digest(), dtype=np.uint8)


def sample_from_mesh(pvtu_path: Path, points_xyz: np.ndarray,
                     projection_method: str = "p1_raw",
                     field_name: str = "Displacement",
                     hct_state: dict | None = None) -> np.ndarray:
    """Project a mesh's nodal velocity field onto query points.

    projection_method:
        "p1_raw"    -- vtkProbeFilter (P1 barycentric interpolation).
                       Fast and, for FSW-style cases where the grid at
                       mesh's natural resolution or coarser, matches the
                       "grid vs mesh Slide 10" story where HCT is
                       demonstrably worse than P1 on refined grids.
                       DEFAULT.
        "hct_cubic" -- SPR nodal-gradient recovery + HCT-3D cubic
                       Bernstein reconstruction (Phase 3b Taylor-fit),
                       evaluated at query points via the Alfeld sub-tet
                       lookup used by scripts/analytic_grid_projection.py.
                       Kept for comparability; slower and (per Slide 10)
                       usually worse on grid centres.
    """
    reader = (vtk.vtkXMLPUnstructuredGridReader()
              if pvtu_path.suffix == ".pvtu"
              else vtk.vtkXMLUnstructuredGridReader())
    reader.SetFileName(str(pvtu_path)); reader.Update()
    ug = reader.GetOutput()

    if projection_method == "p1_raw":
        probe_pts = vtk.vtkPoints()
        probe_pts.SetData(numpy_to_vtk(points_xyz.astype(np.float64),
                                        deep=True))
        probe_poly = vtk.vtkPolyData(); probe_poly.SetPoints(probe_pts)
        probe = vtk.vtkProbeFilter()
        probe.SetInputData(probe_poly); probe.SetSourceData(ug); probe.Update()
        return vtk_to_numpy(
            probe.GetOutput().GetPointData().GetArray(field_name)
        ).astype(np.float64)

    if projection_method == "hct_cubic":
        from jaxtrace.gpu.recovery.hct3d import (
            ALFELD_SUBTET_PARENT_VERTS, bernstein_cubic_evaluate,
        )
        if hct_state is None:
            hct_state = build_hct_projector(pvtu_path, field_name=field_name,
                                             cache_path=None, verbose=True)
        pts_mesh = hct_state["pts_mesh"]
        conn = hct_state["conn"]
        hct_coeffs = hct_state["hct_coeffs"]
        alfeld_centroids = hct_state["alfeld_centroids"]
        ug_hct = hct_state["ug"]

        locator = vtk.vtkCellLocator()
        locator.SetDataSet(ug_hct); locator.BuildLocator()
        n_q = points_xyz.shape[0]
        v_out = np.zeros((n_q, 3), dtype=np.float64)
        cell = vtk.vtkGenericCell()
        pcoords = [0.0, 0.0, 0.0]
        weights_parent = [0.0, 0.0, 0.0, 0.0]
        for i in range(n_q):
            p = points_xyz[i]
            cid = locator.FindCell(p, 1e-6, cell, pcoords, weights_parent)
            if cid < 0:
                continue
            w_parent = np.asarray(weights_parent[:4], dtype=np.float64)
            s = int(np.argmin(w_parent))
            jkl = ALFELD_SUBTET_PARENT_VERTS[s]
            tet_nodes = conn[cid]
            v_j = pts_mesh[tet_nodes[jkl[0]]]
            v_k = pts_mesh[tet_nodes[jkl[1]]]
            v_l = pts_mesh[tet_nodes[jkl[2]]]
            v_c = alfeld_centroids[cid]
            M = np.column_stack([v_j - v_c, v_k - v_c, v_l - v_c])
            try:
                bjkl = np.linalg.solve(M, p - v_c)
            except np.linalg.LinAlgError:
                continue
            bvc = 1.0 - bjkl.sum()
            bary = np.array([bjkl[0], bjkl[1], bjkl[2], bvc],
                            dtype=np.float64)
            bary = np.maximum(bary, -1e-6)
            v_out[i] = bernstein_cubic_evaluate(hct_coeffs[cid, s], bary)
        return v_out

    raise ValueError(f"unknown projection_method: {projection_method}")


def cell_centres_of(block: dict) -> np.ndarray:
    xmin = block["xmin"]; xmax = block["xmax"]; nx, ny, nz = block["n_cells"]
    dx = (xmax - xmin) / np.array([nx, ny, nz], dtype=np.float64)
    xs = xmin[0] + (np.arange(nx) + 0.5) * dx[0]
    ys = xmin[1] + (np.arange(ny) + 0.5) * dx[1]
    zs = xmin[2] + (np.arange(nz) + 0.5) * dx[2]
    X, Y, Z = np.meshgrid(xs, ys, zs, indexing="ij")
    return np.column_stack([X.ravel(), Y.ravel(), Z.ravel()])


# ---------------------------------------------------------------------------
# VTU geometry writer per block + a .vtm wrapper
# ---------------------------------------------------------------------------

def write_block_vtu(out_path: Path, block: dict, v_flat: np.ndarray,
                    block_index: int) -> None:
    """Write the block's hex-cell geometry as a VTU with per-cell |v|
    and full v-vector attached for ParaView colouring."""
    xmin = block["xmin"]; xmax = block["xmax"]; nx, ny, nz = block["n_cells"]
    dx = (xmax - xmin) / np.array([nx, ny, nz], dtype=np.float64)
    cxs = xmin[0] + np.arange(nx + 1) * dx[0]
    cys = xmin[1] + np.arange(ny + 1) * dx[1]
    czs = xmin[2] + np.arange(nz + 1) * dx[2]
    X, Y, Z = np.meshgrid(cxs, cys, czs, indexing="ij")
    pts = np.column_stack([X.ravel(), Y.ravel(), Z.ravel()])
    idx = lambda i, j, k: (i * (ny + 1) + j) * (nz + 1) + k
    n_cells = nx * ny * nz
    conn = np.empty((n_cells, 8), dtype=np.int64)
    c = 0
    for i in range(nx):
        for j in range(ny):
            for k in range(nz):
                conn[c, 0] = idx(i,     j,     k    )
                conn[c, 1] = idx(i + 1, j,     k    )
                conn[c, 2] = idx(i + 1, j + 1, k    )
                conn[c, 3] = idx(i,     j + 1, k    )
                conn[c, 4] = idx(i,     j,     k + 1)
                conn[c, 5] = idx(i + 1, j,     k + 1)
                conn[c, 6] = idx(i + 1, j + 1, k + 1)
                conn[c, 7] = idx(i,     j + 1, k + 1)
                c += 1

    ug = vtk.vtkUnstructuredGrid()
    vpts = vtk.vtkPoints()
    vpts.SetData(numpy_to_vtk(pts.astype(np.float64), deep=True))
    ug.SetPoints(vpts)
    id_arr = np.empty(9 * n_cells, dtype=np.int64)
    id_arr[0::9] = 8
    for kk in range(8):
        id_arr[kk + 1::9] = conn[:, kk]
    cell_arr = vtk.vtkCellArray()
    cell_arr.SetCells(n_cells, numpy_to_vtkIdTypeArray(id_arr, deep=True))
    cell_types = np.full(n_cells, vtk.VTK_HEXAHEDRON, dtype=np.uint8)
    ug.SetCells(numpy_to_vtk(cell_types, deep=True,
                              array_type=vtk.VTK_UNSIGNED_CHAR),
                cell_arr)
    v = v_flat.reshape(-1, 3).astype(np.float32)
    v_mag = np.linalg.norm(v, axis=1)
    varr = numpy_to_vtk(v, deep=True); varr.SetName("v"); varr.SetNumberOfComponents(3)
    marr = numpy_to_vtk(v_mag, deep=True); marr.SetName("v_mag")
    barr = numpy_to_vtk(np.full(n_cells, block_index, dtype=np.int32), deep=True)
    barr.SetName("block_index")
    ug.GetCellData().AddArray(varr)
    ug.GetCellData().AddArray(marr)
    ug.GetCellData().AddArray(barr)

    w = vtk.vtkXMLUnstructuredGridWriter()
    w.SetFileName(str(out_path))
    w.SetInputData(ug)
    w.SetDataModeToBinary()
    w.SetCompressorTypeToZLib()
    w.Write()


def write_vtm_wrapper(vtm_path: Path, per_block_paths: list[Path]) -> None:
    """Small multi-block wrapper so ParaView can open all blocks with one click."""
    body = "\n".join(
        f'    <DataSet index="{i}" file="{p.name}" name="block_{i}"/>'
        for i, p in enumerate(per_block_paths)
    )
    vtm_path.write_text(
        f'<?xml version="1.0"?>\n'
        f'<VTKFile type="vtkMultiBlockDataSet" version="1.0">\n'
        f'  <vtkMultiBlockDataSet>\n{body}\n  </vtkMultiBlockDataSet>\n'
        f'</VTKFile>\n'
    )


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def _fmt_block_summary(blocks: list[dict]) -> str:
    lines = []
    for i, b in enumerate(blocks):
        n = b["n_cells"]
        xmin, xmax = b["xmin"], b["xmax"]
        n_cells = int(np.prod(n))
        lines.append(f"        block {i}: n={n}, "
                     f"x=[{xmin[0]:g}, {xmax[0]:g}], "
                     f"y=[{xmin[1]:g}, {xmax[1]:g}], "
                     f"z=[{xmin[2]:g}, {xmax[2]:g}]  "
                     f"({n_cells:,} cells)")
    return "\n".join(lines)


def _fmt_block_meta(blocks: list[dict]) -> str:
    lines = []
    for b in blocks:
        xmin_tuple = tuple(float(v) for v in b["xmin"])
        xmax_tuple = tuple(float(v) for v in b["xmax"])
        n_tuple = tuple(int(v) for v in b["n_cells"])
        lines.append(f"    ({xmin_tuple!r}, {xmax_tuple!r}, {n_tuple!r}),")
    return "\n".join(lines)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--source", choices=["analytic", "mesh"], required=True)
    ap.add_argument("--source-module", type=Path)
    ap.add_argument("--source-pvtu", type=Path)
    ap.add_argument("--bbox", type=float, nargs=6, required=True,
                    metavar=("XMIN", "XMAX", "YMIN", "YMAX", "ZMIN", "ZMAX"))
    ap.add_argument("--base-n", type=int, nargs=3, required=True)
    ap.add_argument("--grid-type",
                    choices=["uniform", "2lvl", "4lvl", "5lvl", "malmo"],
                    required=True,
                    help="'uniform' | '2lvl' | '4lvl' as before, plus "
                         "'malmo' which extracts per-depth bboxes + "
                         "cube edges from the FOM's mesh-aligned Morton "
                         "octree (jaxtrace.gpu.search.morton_octree_builder). "
                         "Requires --source mesh.")
    ap.add_argument("--malmo-max-depth", type=int, default=None,
                    help="For --grid-type malmo: cap the deepest MALMO "
                         "depth used.  Default: all depths present in "
                         "the mesh's octree.")
    ap.add_argument("--malmo-cells-per-edge", type=int, default=1,
                    help="For --grid-type malmo: grid cell size = MALMO "
                         "cube edge / this factor.  1 (default) matches "
                         "MALMO exactly; 2 doubles the grid resolution "
                         "in every refined level.")
    ap.add_argument("--malmo-leaf-capacity", type=int, default=256,
                    help="For --grid-type malmo: leaf_capacity passed to "
                         "build_global_morton_octree.  Default 256 "
                         "matches the tracker.")
    ap.add_argument("--refine-r1", type=float, default=None,
                    help="Half-extent of the 2x-refined block (m). Required for 2lvl/4lvl.")
    ap.add_argument("--refine-r2", type=float, default=None,
                    help="Half-extent of the 4x-refined block (m). Required for 4lvl and 5lvl.")
    ap.add_argument("--refine-r3", type=float, default=None,
                    help="Half-extent of the 8x-refined block (m). Required for 5lvl.")
    ap.add_argument("--interp",
                    choices=["trilinear", "tricubic", "nearest"],
                    default="trilinear",
                    help="Per-block interpolation.  'trilinear' (C0, "
                         "default) matches the analytic-case runs. "
                         "'tricubic' uses Catmull-Rom cardinal cubic "
                         "(C1, 4x4x4 stencil per query, no gradient "
                         "input needed).  'nearest' is a diagnostic.")
    ap.add_argument("--mesh-projection", choices=["p1_raw", "hct_cubic"],
                    default="p1_raw",
                    help="Projection method used when --source mesh. "
                         "'p1_raw' (default) uses vtkProbeFilter (fast, "
                         "matches Slide 10 finding that HCT is worse on "
                         "grid centres). 'hct_cubic' runs SPR + Alfeld "
                         "Bernstein reconstruction (slower).")
    ap.add_argument("--hct-cache", type=Path, default=None,
                    help="Path to cache the per-case HCT-3D state "
                         "(SPR + Alfeld + Bernstein coeffs). Only used "
                         "when --mesh-projection hct_cubic. When set, "
                         "the first build for a case writes the cache; "
                         "subsequent builds for the same case reuse it "
                         "and skip SPR entirely. Recommend one cache "
                         "path per case dir.")
    ap.add_argument("--mesh-field", type=str, default="Displacement",
                    help="Name of the nodal field to project when "
                         "--source mesh. Default 'Displacement' matches "
                         "both the FSW FOM PVTUs and the analytic "
                         "recirc_2026/rot_cyl_2026 test cases.")
    ap.add_argument("--out", type=Path, required=True,
                    help="Path to the generated .py module.  A sibling "
                         "<stem>.npz stores per-block velocity, and "
                         "<stem>_geom_bK.vtu / <stem>_geom.vtm store "
                         "the ParaView geometry.")
    args = ap.parse_args()

    if args.grid_type in ("2lvl", "4lvl", "5lvl") and args.refine_r1 is None:
        raise SystemExit(f"--grid-type {args.grid_type} requires --refine-r1")
    if args.grid_type in ("4lvl", "5lvl") and args.refine_r2 is None:
        raise SystemExit(f"--grid-type {args.grid_type} requires --refine-r2")
    if args.grid_type == "5lvl" and args.refine_r3 is None:
        raise SystemExit("--grid-type 5lvl requires --refine-r3")

    if args.grid_type == "malmo":
        if args.source != "mesh":
            raise SystemExit("--grid-type malmo requires --source mesh "
                             "(needs the FOM PVTU to build the octree).")
        blocks = make_malmo_aligned_hier_grid(
            args.source_pvtu, tuple(args.bbox),
            leaf_capacity=args.malmo_leaf_capacity,
            max_depths=args.malmo_max_depth,
            cells_per_edge=args.malmo_cells_per_edge,
            verbose=True,
        )
    else:
        blocks = make_hier_grid(tuple(args.bbox), tuple(args.base_n),
                                args.grid_type,
                                args.refine_r1 or 0.0,
                                args.refine_r2 or 0.0,
                                args.refine_r3 or 0.0)
    print(f"[hier-grid] {args.grid_type}: {len(blocks)} block(s) "
          f"(finest first)")
    for i, b in enumerate(blocks):
        n = b["n_cells"]
        print(f"  block {i}: n={n}, x∈[{b['xmin'][0]:g},{b['xmax'][0]:g}], "
              f"cells={int(np.prod(n)):,}")

    # Pre-build the HCT projector once per invocation (loads cache if
    # present).  For p1_raw this is None and each per-block call just
    # runs vtkProbeFilter.
    hct_state = None
    if args.source == "mesh" and args.mesh_projection == "hct_cubic":
        hct_state = build_hct_projector(
            args.source_pvtu, field_name=args.mesh_field,
            cache_path=args.hct_cache, verbose=True)

    # Sample velocity per block at cell centres
    v_flat_per_block = []
    for i, b in enumerate(blocks):
        centres = cell_centres_of(b)
        if args.source == "analytic":
            v = sample_from_analytic(args.source_module, centres)
        else:
            v = sample_from_mesh(args.source_pvtu, centres,
                                 projection_method=args.mesh_projection,
                                 field_name=args.mesh_field,
                                 hct_state=hct_state)
        v_flat_per_block.append(v.astype(np.float32))
        print(f"    block {i}: sampled {centres.shape[0]:,} cell centres")

    # Write npz (keys v_0, v_1, ...)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    npz_path = args.out.with_suffix(".npz")
    np.savez_compressed(
        npz_path,
        **{f"v_{i}": v for i, v in enumerate(v_flat_per_block)},
    )
    print(f"[hier-grid] wrote {npz_path}")

    # Write per-block VTU geometry + a vtm wrapper
    per_block_vtu = []
    for i, (b, v) in enumerate(zip(blocks, v_flat_per_block)):
        vtu = args.out.parent / f"{args.out.stem}_geom_b{i}.vtu"
        write_block_vtu(vtu, b, v, block_index=i)
        per_block_vtu.append(vtu)
        print(f"[hier-grid] wrote {vtu.name}")
    vtm = args.out.parent / f"{args.out.stem}_geom.vtm"
    write_vtm_wrapper(vtm, per_block_vtu)
    print(f"[hier-grid] wrote {vtm.name}  (open in ParaView to see all blocks)")

    # Write the .py module
    src = TEMPLATE.format(
        case_label=args.out.stem,
        source_desc=(f"analytic:{args.source_module.name}"
                     if args.source == "analytic"
                     else f"mesh:{args.source_pvtu.name}"),
        n_blocks=len(blocks),
        block_summary_indented=_fmt_block_summary(blocks),
        block_meta_repr=_fmt_block_meta(blocks),
        interp=args.interp,
        npz_name=npz_path.name,
        velocity_dispatch=_make_velocity_dispatch(len(blocks)),
    )
    args.out.write_text(src)
    print(f"[hier-grid] wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
